### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by DorCoMaNdO** [Eisbison/TheOtherRoles#1]
GPLv3 gives one the right to access the code of software licensed by it, it also prevents anyone from denying said right, meaning that any code using GPL code, derivatives, is required to use GPLv3 and provide the code.

So now, where's the code?

**Comment by Eisbison** [comment]
My bad, I will add the source code tomorrow.

**Comment by Eisbison** [comment]
There are no libraries missing. We are not using Reactor anymore and we're not using anything instead. All the sources are in the sources folder. You're right about the project file, I somehow missed that one. I'll push it asap, but the rest is all there :))

**Comment by nokoji** [comment]
Shame on me :P Keep up the good work!
