### ISSUE TITLE
new remaining tasks info

### ISSUE THREAD

**Issue by Osahashi** [Eisbison/TheOtherRoles#101]
hello, just a small feedback from a few streams I have seen, people would like to deactivate the new remaining task info complete, for themselves and not only for the other players. Could you please add the possibility to deactivate the (0/10).

The role info is cool, chat asks a lot about the current role and with the role visible the streamer doesn't get that many questions. 

Thanks and awesome mod guys! :)

**Comment by EoF-1141** [comment]
Why should the Task Completion not be shown on the player?

**Comment by Osahashi** [comment]
- Chat ask constantly what that number is and don't understand it without explanation.
- You already can see all your tasks and information in the overlay
- Tasks are kinda unimportant with the mod, there is no task win anymore

**Comment by EoF-1141** [comment]
Task Counter will be moved to Task Tab, so Task count can be seen when collapsed.
