### ISSUE TITLE
Collecting from unknown thread since 2.5.1

### ISSUE THREAD

**Issue by Philipp2102** [Eisbison/TheOtherRoles#103]
[Among Us.gc.log](https://github.com/Eisbison/TheOtherRoles/files/6401093/Among.Us.gc.log)
![Unbenannt](https://user-images.githubusercontent.com/83426972/116607018-c6e01d00-a931-11eb-8ab7-fca239a97017.PNG)

**Comment by jerem2772** [comment]
I have the same problem. If I delete the folder "among us" in %AppData%\LocalLow\Innersloth
I can restart the game once and then I have the same problem again.

**Comment by EoF-1141** [comment]
Not sure when Hotfix comes on this public repo.
but in the meantime you can see if
https://github.com/EoF-1141/TheOtherRoles/releases/tag/v2.5.1
fixes this for you.
(You may still have to go into `%AppData%\..\LocalLow\Innersloth\Among Us` and delete the `RegionInfo.json` file for the first start. But afterwards it should run)
