### ISSUE TITLE
"You were Banned for hacking"

### ISSUE THREAD

**Issue by SzudemARAH** [Eisbison/TheOtherRoles#104]
Today I tried out the newest Version of the game but couldn´t play. After starting the game (pressing start button) it said: "You were banned for hacking. Please Stop!"
Is this an issue that comes with the new update? Is it not compatible?

**Comment by SzudemARAH** [comment]
I already reinstalled the game twice and also the mod. My friends had the same problem. I don´t know where this comes from :/

**Comment by Eisbison** [comment]
Anyone else with the same issue?

**Comment by Eisbison** [comment]
You can (and should) play on a custom server, that will resolve this issue.

**Comment by FerbFloo** [comment]
Yeah, that happened to me too...

**Comment by Eisbison** [comment]
It happens every now and then and the end of games (not mod related). @FerbFloo when does this error show up on your side?

**Comment by FerbFloo** [comment]
It happened in the last update, when a friend and I were testing out the new role. He joined my lobby with three instances, while I was only using one, yet, i got "banned for hacking"... It hasn't happened since, so I didn't think that much of it.

**Comment by Filledebatteur4** [comment]
I have this issue but only on my private server. As soon as someone else joins the game we all get kicked and "Banned for Hacking"

**Comment by amsyarasyiq** [comment]
> I have this issue but only on my private server. As soon as someone else joins the game we all get kicked and "Banned for Hacking"

disable anticheat on your private server

**Comment by MrFawkes1337** [comment]
using Custom Impostor Server on latest update, change Anticheat and BanIpFromGame to false, save changes and restart. If you're on official servers, Can't really help there. Afaik Eisbison's patch for amBanned should work as long as everyone has the mod, even without. I have no issues on latest version, tested both Official and Private.

**Comment by Eisbison** [comment]
Can we close this issue?

**Comment by FerbFloo** [comment]
I feel so, yeah. If it happens to anyone again, they can open a new issue... Maybe that way you'll be able to find a trigger...

**Comment by Fanmade** [comment]
We were playing with 9 people together just using this one mod and this happened to most of us at least once.
