### ISSUE TITLE
FPS drops only with "The Other Roles" 

### ISSUE THREAD

**Issue by Doflamongo** [Eisbison/TheOtherRoles#107]
Hello everybody, 

I have a little problem...
Among us vanilla runs smooth with 300fps..
but when I start the TOR mod, I have fps drops to 5fps  like every 3 seconds and idk why. I tried everything, 
I reinstalled Among us, I switched it to the SSD and even changed my nvidia settings, but the FPS drops are stilll the same and they only happen while I run among us with The Other Roles.

I might need some help here. 
The problems started after TOR 1.8.2.rar

CPU-Marke: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
DirectX-Karte: NVIDIA GeForce GTX 1050 Ti
Windows 8.1 (64 Bit)

any ideas?

**Comment by Eisbison** [comment]
I'd have to run some tests with you ( or with one of the few ppl that  have the problem. Do you think you can run some tests with me next week?

**Comment by LeonMarcel-HD** [comment]
I have these FPS drops aswell. I tried to replicate it rn but I'm not sure if it got fixed but I will see later today because we're playing again.

**Comment by Doflamongo** [comment]
I'd appreciate it. Let me know when you'd like to do it. 

What does rn in "replicate it rn" mean?

**Comment by LeonMarcel-HD** [comment]
Yesterday I had FPS drops but today I didn't had them so it is inconsistant for me

**Comment by Doflamongo** [comment]
Soo.. when would u like to do the tests eisbison

**Comment by Doflamongo** [comment]
Moin eisbison, I just tried the new version (2.5.1) and there're still the same problems. I even tried to host a lobby but it doesn't matter. Any new ideas? I'm still looking for a solution. Could it be that win 8.1 is the problem?

**Comment by amsyarasyiq** [comment]
> Moin eisbison, I just tried the new version (2.5.1) and there're still the same problems. I even tried to host a lobby but it doesn't matter. Any new ideas? I'm still looking for a solution. Could it be that win 8.1 is the problem?

1. Go to your Among Us directory/BepInEx/ and open LogOutput.log using Notepad or any software you have.
2. Copy all the content there and paste it here

**Comment by HutMitMann** [comment]
I guess all of your RAM is not the best, i had the same problems... With each role in addition the RAM is used more and more, i think its an Performance Problem within the Code. It could be fixed, but hey, he is doing it in his free time ;) it takes a while to re-code this for a performance Boost!

**Comment by iceman1183** [comment]
> I guess all of your RAM is not the best, i had the same problems... With each role in addition the RAM is used more and more, i think its an Performance Problem within the Code. It could be fixed, but hey, he is doing it in his free time ;) it takes a while to re-code this for a performance Boost!

I have 40gigs of ram. I don‘t think it’s RAM caused. Also I got another problem, that I always disconnect when the lobby is not open again after a game. If the lobby is open after the game I joyn the lobby normally...

**Comment by HutMitMann** [comment]
DDR3 or DDR4 with how many Hz???

**Comment by iceman1183** [comment]
> DDR3 or DDR4 with how many Hz???

DDR4 2667Mhz

**Comment by amsyarasyiq** [comment]
Did you tried turn on/off VSync?

**Comment by iceman1183** [comment]
> Did you tried turning on/off VSync?

Vsync on/off ; Fullscreen on/off ; different resolutions...
Reinstall original version, creating new Mod Folder, Trying a Mod folder from a friend,....

**Comment by DDaryll** [comment]
yea ive the same problem, tried like everything too
nvdia settings, vsync stuff, turning other programs off

dont know if there r to many roles or to many hats or if unity is just crap xD 
in freeplay there r some stutter, but as soon as i play in a full lobby.. its lagging(stuttern fps drops) as hell

**Comment by Doflamongo** [comment]
> 1. /BepInEx/ and open LogOutput.log

[Message: Preloader] BepInEx 6.0.0-be.353 - Among Us
[Message: Preloader] BLEEDING EDGE Build #353 from c49f1b42f6d25e5b32b0557b8ae30bbce497574a at master
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2020.2.6.9052483
[Message: Preloader] Generating Il2CppUnhollower assemblies
[Info   : Preloader] Generating Il2CppDumper intermediate assemblies
[Info   : Preloader] Executing Il2CppUnhollower generator
[Info   :Unhollower] Reading assemblies... 
[Info   :Unhollower] Done in 00:00:00.9555860
[Info   :Unhollower] Computing renames... 
[Info   :Unhollower] Done in 00:00:00.0223580
[Info   :Unhollower] Creating typedefs... 
[Info   :Unhollower] Done in 00:00:00.0408169
[Info   :Unhollower] Computing struct blittability... 
[Info   :Unhollower] Done in 00:00:00.0023936
[Info   :Unhollower] Filling typedefs... 
[Info   :Unhollower] Done in 00:00:00.0159908
[Info   :Unhollower] Filling generic constraints... 
[Info   :Unhollower] Done in 00:00:00.0012133
[Info   :Unhollower] Creating members... 
[Info   :Unhollower] Done in 00:00:00.5499148
[Info   :Unhollower] Scanning method cross-references... 
[Info   :Unhollower] Done in 00:00:01.1888342
[Info   :Unhollower] Finalizing method declarations... 
[Info   :Unhollower] Done in 00:00:00.8221458
[Info   :Unhollower] 1 total potentially dead methods
[Info   :Unhollower] Filling method parameters... 
[Info   :Unhollower] Done in 00:00:00.1458514
[Info   :Unhollower] Creating static constructors... 
[Info   :Unhollower] Done in 00:00:00.2220014
[Info   :Unhollower] Creating value type fields... 
[Info   :Unhollower] Done in 00:00:00.0752248
[Info   :Unhollower] Creating enums... 
[Info   :Unhollower] Done in 00:00:00.0171558
[Info   :Unhollower] Creating IntPtr constructors... 
[Info   :Unhollower] Done in 00:00:00.0194346
[Info   :Unhollower] Creating type getters... 
[Info   :Unhollower] Done in 00:00:00.0439201
[Info   :Unhollower] Creating non-blittable struct constructors... 
[Info   :Unhollower] Done in 00:00:00.0038057
[Info   :Unhollower] Creating generic method static constructors... 
[Info   :Unhollower] Done in 00:00:00.0174692
[Info   :Unhollower] Creating field accessors... 
[Info   :Unhollower] Done in 00:00:00.4125476
[Info   :Unhollower] Filling methods... 
[Info   :Unhollower] Done in 00:00:01.1771889
[Info   :Unhollower] Generating implicit conversions... 
[Info   :Unhollower] Done in 00:00:00.0168252
[Info   :Unhollower] Creating properties... 
[Info   :Unhollower] Done in 00:00:00.0457435
[Warning:Unhollower] Not performing unstripping as unity libs are not specified
[Info   :Unhollower] Generating forwarded types... 
[Info   :Unhollower] Done in 00:00:00.0020404
[Info   :Unhollower] Writing xref cache... 
[Info   :Unhollower] Done in 00:00:00.9980913
[Info   :Unhollower] Writing assemblies... 
[Info   :Unhollower] Done in 00:00:01.4355721
[Info   :Unhollower] Writing method pointer map... 
[Info   :Unhollower] Done in 00:00:00.0527415
[Info   :Unhollower] Done!
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [The Other Roles 2.6.7]
[Message:   BepInEx] Chainloader startup complete


> > Moin eisbison, I just tried the new version (2.5.1) and there're still the same problems. I even tried to host a lobby but it doesn't matter. Any new ideas? I'm still looking for a solution. Could it be that win 8.1 is the problem?
> 
> 1. Go to your Among Us directory/BepInEx/ and open LogOutput.log using Notepad or any software you have.
> 2. Copy all the content there and paste it here

**Comment by iceman1183** [comment]
1. /BepInEx/ and open LogOutput.log

[Message: Preloader] BepInEx 6.0.0-be.353 - Among Us
[Message: Preloader] BLEEDING EDGE Build #353 from c49f1b42f6d25e5b32b0557b8ae30bbce497574a at master
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2020.2.6.9052483
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [The Other Roles 2.6.7]
[Message:   BepInEx] Chainloader startup complete

**Comment by iceman1183** [comment]
Even with the new version it's still the same.

**Comment by nickdeny** [comment]
@Eisbison Old version was freezing every 2-3 seconds and new one is lagging stronger (Especially during sabotage). Playing on Windows 10 (Mac Bootcamp).

**Comment by 4310V343k** [comment]
When you first install TOR FPS spikes every time the hat image is downloaded/being downloaded.
If you can't reproduce the issue after some time of playing the culprit is hat downloader

**Comment by dwd0tcom** [comment]
I guess I found the solution:
For me it was discord, if you enable the game status in discord, among us has insane fps drops. If you rename your Among Us folder in C:\Program Files (x86)\Steam\steamapps\common\ to something like "TheOtherRoles", I have zero fps drops and 60fps.
