### ISSUE TITLE
Unable to join lobbies or create lobbies for others to join

### ISSUE THREAD

**Issue by rushworld** [Eisbison/TheOtherRoles#11]
Ever since the latest version I have been unable to join lobbies or have others join my lobbies. When I join I appear as green with "???" and my lobby screen is a greyed out drop ship.

[Screenshot](https://i.imgur.com/HirSstr.png)

I have reinstalled everything onto a fresh Among Us folder, ran the exe as administrator, added the modded copy of the exe to the firewall... no luck.

**Comment by R4v3ncl4w** [comment]
To add onto that i tried a VPN, 2 different PCs and a VM. No Luck at all. I can join public lobbies without a problem and normal Among Us and other mods work. 

Looks like some problem with the internet connection but at the moment cant really figure out why. Tested mobile Hotspot and that worked. Do i need to forward some Ports or anything?

**Comment by Schlawinergames** [comment]
Got the same problem...

**Comment by ThaSiouL** [comment]
One person in our group has the same problem. Literally every time he rejoins the lobby he gets a ??? and has to rejoin. we have completely deleted reinstalled among us and the mods, deleted the LocalLow Innersloth folder and reinstalled the c# redist in case there was some kind of bug arising from that. It still happens to him and only to him. 

He also gets random glitches like not seeing others during rounds and just not seeing the meeting screen. These problems only appear with this mod.

**Comment by Schlawinergames** [comment]
> One person in our group has the same problem. Literally every time he rejoins the lobby after a game he enters the lobby corrupted and has to rejoin. He has completely deleted reinstalled among us and the mods, deleted the LocalLow Innersloth folder and reinstalled the c# redist in case there was some kind of bug arising from that. It still happens to him and only to him.
> 
> He also gets random glitches like not seeing others during rounds and just not seeing the meeting screen. These problems only appear with this mod. Unmodded and other mods seem to work fine.

Did it work?

**Comment by ThaSiouL** [comment]
it works when he joins from the base screen but not when rejoining after a game. and he gets like 75% of all desyncs and bugs we see.

**Comment by Arbezilics** [comment]
Ive been having this same issue myself for about 2 weeks now with this mod and the Town of Us mod. I have tried everything but I have no idea whats wrong. Ive tried playing the mod on the unupdated version of Among Us and it doesnt work that way either, but almost everyone else in the group I play with has no issues besides one person who just has bad internet.

**Comment by VanomPain** [comment]
I've the same problem : /

**Comment by SweetYukiUchiha** [comment]
I also have this broblem and it only work then i your my phone as an Hotspot. But sometime my pc lose it and i got kicked. I think it somethink on the Inet  box (stage).

**Comment by Arbezilics** [comment]
Update: I have gotten it working by disabling my VPN, make sure you arent playing with one on!!

**Comment by SvenM95** [comment]
Ok guys, the VPN hint brought me to the idee that is has to do with some Network settings.So i tried a several network settings and the solution for me was to deaktivate "block fragmented packets" in the firewall settings from my router. Please check this and let me know if it worked for you guys.

**Comment by Eisbison** [comment]
Thanks for your contributions here. The new build should contain a fix for this, so I'll close the issue. If you got any problems with the update, we'll reopen it ✅
