### ISSUE TITLE
Among us crashes after opening once

### ISSUE THREAD

**Issue by captv1etnam** [Eisbison/TheOtherRoles#110]
After i downloaded the Other Roles mod 2.5.1 i opened the game and it worked but then after closing the game it didn't open again. There was just the message "Collecting from unknown thread". Can someone help me?

**Comment by nossi80** [comment]
Same here. Yesterday needed 3 attemps to start. Today 5.

**Comment by Eisbison** [comment]
Please test if the fix included in v2.6.0 works for you. If it does, please let me know.

**Comment by vhammerschmidt** [comment]
seems to happen on 2.6 aswell.

**Comment by nossi80** [comment]
> Please test if the fix included in v2.6.0 works for you. If it does, please let me know.

Yesterday with 2.6.1 no Problems

**Comment by Eisbison** [comment]
@captv1etnam Same for you?

**Comment by captv1etnam** [comment]
Everything alright with 2.6.0. never had a problem again
