### ISSUE TITLE
"Number of crewmate roles" can bug lovers

### ISSUE THREAD

**Issue by nokoji** [Eisbison/TheOtherRoles#112]
It's possible to have 1 lover with no counterpart if the other lover happens to get assigned "crewmate" with the new role assignment system

**Comment by Eisbison** [comment]
Do you have a set of settings with which we can reproduce this? Because I've not yet been able to do that, and looking at the code I just don't see where things are failing :)

**Comment by EoF-1141** [comment]
Role Assignment has been reworked multiple times.
I don't seen how this would happen with the assignment - reopen this if it happens again. (With settings for repro preferable)
