### ISSUE TITLE
v2.6.1 Does not start with the mod

### ISSUE THREAD

**Issue by Bamkiller** [Eisbison/TheOtherRoles#115]
When I (and my friends) start Among us with the mod, it just start the normal Among us. We installed everything correctly (like everytime).
![911120306513c57269863610ef5a3ef2](https://user-images.githubusercontent.com/67231300/117723652-f0772f00-b1e2-11eb-8720-9eaf330c0d0e.png)

**Comment by JoniG59** [comment]
is it possible, that you have Among Us version 2021.5.10s? 
if yes the reason that the mod does not load is that the Among Us version is to new for Mod-target (v 2021.4.14s)

**Comment by Bamkiller** [comment]
can I delete it again?

**Comment by Bamkiller** [comment]
> is it possible, that you have Among Us version 2021.5.10s in the folder?
> if yes the reason that the mod does not load is that the Among Us version is to new for Mod-target (v 2021.4.14s)

Can I delete I again somehow?

**Comment by Bakeneko** [comment]
Use [DepotDownloader](https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.6), this is an utility to download specific game packages from [steamdb](https://steamdb.info). Extract the release, open a terminal in the folder and execute command:
`depotdownloader.bat -app 945360 -depot 945361 -manifest 1328515537648622656 -user <YourSteamUsername> -dir "Among Us 2020.4.14s"` 

You will be prompt to enter your Steam password (Steam won't let you download paid content without authentication).
The 2020.4.14 version files will be downloaded in a "Among Us 2020.4.14s" folder.
I recommend to copy this folder somewhere and use this version to play with mods and keep the "up-to-date Steam client version" for vanilla games.
