### ISSUE TITLE
Role proposal

### ISSUE THREAD

**Issue by JeSuisUneLicorne** [Eisbison/TheOtherRoles#119]
The Trapper (Der Fallensteller) (Impostorrole)

Once per meeting, he can sabotage a task, or place a trap (traps cant be used near the alarm button / reactor or o2 sabotage).

Sabotaged tasks kills the crewmate doing this task instantly (only 1 kill per meeting/round). We need some cool kill animations, like cable tasks will electrify the crewmate or the med scan will laaaazzzer him instead. 

Traps stuns the crewmate for 5/7/10 seconds. Would be funny if they get sused for being a warlock or cant report the body soon enough.

Edit: I proposed the trapper in one of Eisbisons streams - he might remember.
(Twitch is DaFishbone - Ingame is DrSuspect (sometimes: TheSuspect))

**Comment by Netskeh** [comment]
I think the premise is interesting - to rephrase and make sure I understood what your idea is:

- Sabotage task -> kills the first crewmate who interacts with that task.
- Place regular trap -> (invisible?) to the players and somewhere on the ground which slows down / makes the cremate stop at the stop for a specified amount of time.

Can that imposter role also call sabotages, use vents etc? What is your take on this?
My idea would be, yes the Trapper should be able to do both, as I believe the balancing factor would be as you suggested only 1 kill per round, while the normal traps are cooldown based.

**Comment by JeSuisUneLicorne** [comment]
Kinda.

* Sabotage task -> Yes. Once per round. By round I mean once per meeting. Otherwise it would be to overpowered.
* Regular Trap -> Yes, it should be invisible. Can be placed on the ground with some exceptions, like near the alarm button or maybe in the door area. Traps should not kill, but stop/ground the crewmates and neutral roles.

That imposter role can also call sabotages, use vents, etc.
For balancing reasons I would suggest 1 token (sabotage task or trap) per round. Or 1 sabotage task and up to 2 traps per round. Not used traps should be cleared after emergency meeting.

**Comment by Kotlin-Native** [comment]
Is the second imposter affected by the regular trap?
Is there any way to see a saboatged task before doing that as crewmate?

**Comment by JeSuisUneLicorne** [comment]
Is the second imposter affected by the regular trap? -> No. But it could be optional!

 Is there any way to see a saboatged task before doing that as crewmate? -> No.

**Comment by JeSuisUneLicorne** [comment]
Will there be a drawback to the impostor (like Warlock gets frozen)? -> No.

 Is the trap/sabotage activating by itself or does the impostor need to press a remote kill button? -> Itself.
 
 Is the trap/sabotage set permanently or only for some time (e.g. 20 seconds) -> Till next meeting.
 
 Does the trap/sabotage trigger the kill cooldown? -> Trap should be extra but shares the CD with sabotage. But if the sabotage kills it should share the kill CD.

**Comment by Eisbison** [comment]
As this is not really a issue, please post it on our discord in the suggestions channel. I don't want to keep so many "issues" open with suggestions that might or might not make it into the game, that's the reason we've set up the suggestion system in the first place ;)
