### ISSUE TITLE
Seer doesn't see flashs or souls

### ISSUE THREAD

**Issue by teshi24** [Eisbison/TheOtherRoles#121]
We've played with the standard options for the seer, both skills enabled.
However, none of the skills got triggered - multiple players with the seer role did not see a flash on the kills & no gosths where flying around.

**Comment by SinJin59** [comment]
This is a known "Bug" (but normally only for Death Flashs). They don´t know yet really what it is causing. Sometimes it works and sometimes not. They´re working on it!

**Comment by orangeNKeks** [comment]
I think I found the issue for this in the Seer class itself.
In the clearAndReload method it says

`mode = CustomOptionHolder.medicShowShielded.getSelection();`

**Comment by Eisbison** [comment]
Sad life, @orangeNKeks  you're the best :D

**Comment by EoF-1141** [comment]
Fixed in 2.6.4
