### ISSUE TITLE
The Medic

### ISSUE THREAD

**Issue by squiiirtle** [Eisbison/TheOtherRoles#122]
Dear Eisbison

I wanna tell u that theres a big issue with the Meidc. He cant give anyone a shield and he losses his shield without touching the shield button.

Thats all. If I find an another issue ill tell it in a report

Stay healthy 

squiiirtle aka. Miquel

**Comment by SinJin59** [comment]
On what Version are you playing? In V2.6.3 it worked erything fine for me and others. You got a bit more details when it happened?

**Comment by orangeNKeks** [comment]
I also saw that on 2.6.3 but only in one group of people.

I saw lately that some peoples PCs are that slow that either the round takes over 20 seconds to start (black screen before the red figure appears and you get shown your role) if the PC is the host or the person with the slow PC starts very late in the game.
Could that cause this issue maybe?
As far as I know this haven't happen before 2.6.3

**Comment by Maryjane007** [comment]
That happened to a German streamer too!
