### ISSUE TITLE
VORSCHLAG

### ISSUE THREAD

**Issue by Maryjane007** [Eisbison/TheOtherRoles#127]
Ändere den Downloadweg hier auf GitHub (also, wo du gesagt hast, wie man es downloadet, hier auf GitHub) mit dem Downloadweg von slushiegoose auf der TownOfUs Mod.

Es ist deine Entscheidung, ob du es machst!

**Comment by EoF-1141** [comment]
No idea what that is even supposed to mean.

**Comment by Maryjane007** [comment]
I thought you speak German!
