### ISSUE TITLE
Suggestion: Snitch Settings

### ISSUE THREAD

**Issue by Scamper10** [Eisbison/TheOtherRoles#128]
The snitch is OP, people always just do tasks in the first 2 rounds and vote the imposters out.
Here's a proposal: add an option (toggle) or percentage chance for the snitch to look like a regular crewmate until they are revealed.
Town of Us already has this as a toggle, but this mod is much better, and I would love to see it here too with more customisation...

**Comment by orangeNKeks** [comment]
If you don't do settings to allow someone being crewmate, the snitch will know being it anyhow.

**Comment by Scamper10** [comment]
That doesn't matter because:
1. People don't always know the settings
2. I DO allow 1 regular crewmate in the game

**Comment by EoF-1141** [comment]
If they rush tasks, they also are in risk of getting killed as they are alone more often.
And to be honest - if I'm a standard crewmate I would rush my tasks just as much.

The Impostors also get arrow to the snitch earlier than the snitch does, you can just increase the amount of tasks left, to allow Impostors more time to kill the snitch.
