### ISSUE TITLE
Instant Win

### ISSUE THREAD

**Issue by lenyiion** [Eisbison/TheOtherRoles#130]
Today we played some matches with the mod installed and got some instant wins without even revealing the roles. We have not found out the issue of this even with disabling a few roles and testing if it works. We are on version 2.6.4 btw.

**Comment by tom2208** [comment]
We experienced the same thing. But we got an insta win on another way too: We had a jackel team and the jackel made the last imposter to their sidekick => Crewmates won.

**Comment by Maryjane007** [comment]
Did you use BetterCrewLink because I did and got a lot of instant wins!

**Comment by NoEpicLoot** [comment]
somehwat similar occurence here.

Our imposter was a BadChild and we had a jackal lover who made the lighter-lover their sidekick which resulted in an instant crewmate win
