### ISSUE TITLE
Role proposal: Mimic

### ISSUE THREAD

**Issue by zatho-ger** [Eisbison/TheOtherRoles#131]
Hey,

I had an Idea for a new role. What do you think? An imposter who has the ability to appear as dead body. He can change between this appearance and normal form at any time. When he kills or uses a vent, he will transform to normal form immediately. This can be interesting to lure people who check cams into a trap.

Thanks for your feedback

**Comment by orangeNKeks** [comment]
Which body should be shown?
What happens if a crewmate finds this "fake dead body"?

**Comment by zatho-ger** [comment]
> Which body should be shown?
I thought of his own body. However it might be also interesting to copy his last victim. 

> What happens if a crewmate finds this "fake dead body"?
Depending on the kill-cooldown either the crewmate gets killed, when trying to report or the Mimic is transformed back to normal form.

**Comment by Eisbison** [comment]
As this is not really a issue, please post it on our discord in the suggestions channel. I don't want to keep so many "issues" open with suggestions that might or might not make it into the game, that's the reason we've set up the suggestion system in the first place ;)
