### ISSUE TITLE
Imposter Role Idea - Necromancer

### ISSUE THREAD

**Issue by Lusaphor** [Eisbison/TheOtherRoles#134]
So the premise of the Necromancer is once during a round/game, they can resurrect (shared cooldown with the kill button) a dead crewmate to act as a killer with an adjustable kill timer (settings) and a limit on how far they can travel from the necromancer. Said minion would die at the start of any meetings and/or when the Necromancer is killed. Once the meeting is over they revert to ghost crewmate to complete task they had remaining, but if the imposters win during the round a crewmate is a minion they also get the win, but when a crewmate is a minion their task are considered completed to help balance the extra imposter. This might not be entirely possible, but would be an interesting mechanic to toy around with, and would add to complexity of trying to track down the true imposters.

**Comment by Eisbison** [comment]
As this is not really an issue, please post it on our discord in the suggestions channel. I don't want to keep so many "issues" open with suggestions that might or might not make it into the game, that's the reason we've set up the suggestion system in the first place ;)
