### ISSUE TITLE
Proposal: Show all users + roles in Victory/Defeat Screen

### ISSUE THREAD

**Issue by swNero** [Eisbison/TheOtherRoles#135]
It would be awesome that you could see all users in the end with their roles. I'd like to see the winning group on top (Crew, Impostor, Jakal, Arsonist, ..) and the other existing groups below with the user names and their roles. Sometimes it is really complicated to check in the end why who won against whom.

**Comment by Eisbison** [comment]
Doesn't the new feature of v2.6.6 resolve this issue?

**Comment by Lupo-93** [comment]
The feature was added in [2.6.5](https://github.com/Eisbison/TheOtherRoles/releases/tag/v2.6.5)
