### ISSUE TITLE
Suggestion: Presets to .txt

### ISSUE THREAD

**Issue by HutMitMann** [Eisbison/TheOtherRoles#136]
Hey, what about exportthe presets into a *.txt file and importing that preset into the game? The reason: a group that plays together regularly can "save" their own presets and anyone can open a new game without asking "what was our preset again?" and missing settings?!

Much love Eisbison and team <3

**Comment by pLurchi** [comment]
I think it should be this file: 
"...\steamapps\common\Among Us\BepInEx\config\me.eisbison.theotherroles.cfg"

**Comment by JerryGreen** [comment]
It would be cool if it were possible to copy the settings into buffer as text, then paste it to whatever place I want / share with friends. And, of course, to be able paste them back with CTRL + V or a button (like room code)
