### ISSUE TITLE
Suggestion: Auto-Complete Tasks for erased Jackal

### ISSUE THREAD

**Issue by CaptainKhaid** [Eisbison/TheOtherRoles#142]
Maybe it is possible, if eraser ersaed the Jackal, that some tasks are Auto completed, depending on the game state. 
If the Jackal is erased in endgame, it is hard to win with tasks, if he has to do all tasks from scratch.
For example it would be great, if x tasks get auto-completed, with x being the average completed tasks by Crew.

**Comment by nokoji** [comment]
Correct me if I'm wrong but I thought that the Jackal, although being titled 'Crewmate', remains in team Jackal after getting erased and thus his tasks won't count towards a taskwin?

**Comment by CaptainKhaid** [comment]
As far as I know, an erased jackal/ sidekick turns to crewmate Team and will have to do all tasks from 0 (not sure if sidekick starts at 0 or where he ended before turning sidekick). Because both turn to crewmate role and just can vote sidekick/jackal out.

**Comment by Eisbison** [comment]
I think we can close this because of v2.7.0 :)
