### ISSUE TITLE
ROLE IS GONE EVEN THOUGH NO ERASER

### ISSUE THREAD

**Issue by Maryjane007** [Eisbison/TheOtherRoles#145]
A German streamer played TheOtherRoles and he was medic lover with a person who was jester lover.
And he shielded his lover.

After the first meeting, the streamer wasn't medic lover anymore. 
How is it possible if no eraser in game??

**Comment by Eisbison** [comment]
Shifter?

**Comment by Maryjane007** [comment]
No, because the lovers were together all the time and the shifter wasnt even in game.
