### ISSUE TITLE
(Good) Guesser Vote after death

### ISSUE THREAD

**Issue by Lupo-93** [Eisbison/TheOtherRoles#147]
Version: 2.6.7  
Among Us Version: v2021.5.25.2s  
  
Situation:  
There were 4 players left in the round:  
- Mayor
- Jackal
- Other Crewmate Role
- Good Guesser (me)

I voted the mayor, before guessing jackal on him, and dying.
The mayor voted the Jackal, giving him two votes.
Jackal and other crewmate voted on mayor, giving him two votes as well.
The votes were counted and a 2 / 2 vote draw was shown. But afterwards the mayor got ejected. 

What should happen is one of the two:
- The guesser vote gets invalidated after the guesser dies.
- The guesser vote gets shown correctly.

What happens is: the vote becomes invisible and still counts.

Thank you for the mod, it's a lot of fun!

**Comment by Eisbison** [comment]
Oh I'm dumb... I'll fix it asap
