### ISSUE TITLE
Add option to set "sample" cooldown for morphling

### ISSUE THREAD

**Issue by Erumeldor** [Eisbison/TheOtherRoles#15]
I would love to see an option to change the initial cooldown of the morphling to sample someone.

That's because I would set it to 0, so that you can sample right after the meeting to later morph into someone. Also this cooldown should be the same after you morphed back.

That means:
New Cooldown -> Sample -> Exisiting cooldown -> Morph -> New Cooldown -> Sample -> Existing Cooldown, and so on.

Alternative: Just remove the cooldown completely. I don't see any advantage of that.
Thanks! Nice mod compilation btw! :)

**Comment by FerbFloo** [comment]
I totally agree with that, would argue though, that the Morphling should only be able to sample a crewmate once every round. That would force him to think ahead and plan his plays beforehand.

**Comment by Eisbison** [comment]
We'll change that a bit in todays hotfix. But we'll take it into consideration for a future update
