### ISSUE TITLE
TheOtherRoles not working with latest Among Us update

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [Eisbison/TheOtherRoles#150]
Well, the mod does no longer load since latest update ;)

**Comment by balloplayz** [comment]
update it ebison

**Comment by Eisbison** [comment]
Lol @balloplayz

**Comment by balloplayz** [comment]
please update its a fun mod cant play it anymore

**Comment by balloplayz** [comment]
until updated

**Comment by Eisbison** [comment]
You can, just start Among Us from the game folder of the previous Among Us version and you're good to go. The recent update didn't really add a lot, compared to what was already possible with the latest mod version.... Obviously we'll update it, as we always do. But it'll take its time
