### ISSUE TITLE
Costum Server

### ISSUE THREAD

**Issue by JeSuisUneLicorne** [Eisbison/TheOtherRoles#153]
We played on costum server with the IP 178.63.6.114 - since TOR 2.7.0 it says I have an older version. But I have the latest version of Among Us and TOR. Is there a fix or new IP?

**Comment by Eisbison** [comment]
It also says that if you have a new version, as far as I know.... Was everyone using the newest Among Us version?

**Comment by JeSuisUneLicorne** [comment]
Yep

**Comment by Eisbison** [comment]
Well it seems like Impostor is not ready yet (https://github.com/Impostor/Impostor/pull/423). I'll close this issue for now, since it's not really an issue of TOR :)
