### ISSUE TITLE
Epic Games No Hats

### ISSUE THREAD

**Issue by EinfachEnte** [Eisbison/TheOtherRoles#154]
Hello Team from the Otherroles Mod,
I had a problem in my Among us with Otherroles I had no Hats I downloaded Among us from the Epicgames Store. I had only the Hats from Among us but Not from Otherroles. I hope you can help me
Your faithfuly
EinfachEnte

**Comment by Eisbison** [comment]
Do they show up if you restart the game?

**Comment by EinfachEnte** [comment]
Nope it changed nothing

**Comment by EoF-1141** [comment]
Potentially #158
