### ISSUE TITLE
Custom Hats not in game [Race Condition]

### ISSUE THREAD

**Issue by Mooncake02** [Eisbison/TheOtherRoles#158]
To keep it short. Since 2.7.0 the Hats won't appear for me anymore (Using Steam Among Us). I tried setting up the folder several times (even reinstalling the game itself) but the Hats won't show no matter what.

**Comment by Eisbison** [comment]
Are they being downloaded? (Check the TheOtherHats folder)

**Comment by Abseudus** [comment]
Hey, 
can confirm this, got the same issue. Hats are in the "TheOtherHats"-Folder but are not shown in-game.

**Comment by Mooncake02** [comment]
yeah. not for me. 2 days later and they're still not their. other hats as in the folder though

**Comment by Mooncake02** [comment]
one day*

**Comment by momper14** [comment]
We played with a group of 10 yesterday. All had the same Problem but a restart fixed it for everyone of us.

**Comment by Mooncake02** [comment]
it worked for a few of my friends as well. but mine doesn't want to work. doesn't matter how many times i restart of reinstall and/or redo the game folder. i only see sloth's hats. it worked fine until 2.7.0.

**Comment by MrFawkes1337** [comment]
Seems to be an issue with latest release, as even manually downloading the hats from Github, then installing them as should sometimes causes them not to load for me.

**Comment by EoF-1141** [comment]
Might be related to a race condition, where the Account loading on startup triggers the code that is supposed to add the hats before the hats are done loading.
That specific issue should be solved in the next update.

**Comment by Maryjane007** [comment]
Well, if there are hats in TheOtherHats folder, then drag the folder (TheOtherHats) in the Among Us.exe in your TheOtherRoles folder and put something on.
