### ISSUE TITLE
No joining in privat Lobbys with Epicgames

### ISSUE THREAD

**Issue by EinfachEnte** [Eisbison/TheOtherRoles#159]
Hello Team from TheOtherroles Mod,
My Issue is that I didn't can join a privat Lobby but can create Room and I tryed with my friend He had also epicgames Among us and also don't can join my Lobby but anybody who has not the Otherroles Mod can join the Lobby. I hope you can fix that.
Your faithfuly
EinfachEnte

**Comment by Eisbison** [comment]
I assume that your installation is somehow wrong (probably you're using an outdated among us version....). And an error message would be helpful.... :)

**Comment by EinfachEnte** [comment]
Nvm my Among us Was brocken
