### ISSUE TITLE
new bepinex update breaks updater and hats

### ISSUE THREAD

**Issue by MrFawkes1337** [Eisbison/TheOtherRoles#160]
Bepinex 6.0.0-Reactor21, updater spits the following error:

[Error  :    Detour] System.TypeLoadException: Could not load type of field 'TheOtherRoles.ModUpdater+<checkForUpdate>d__8:<http>5__1' (2) due to: Could not resolve type with token 0100009c from typeref (expected class 'System.Net.Http.HttpClient' in assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Net.Http.HttpClient member:(null)
  at TheOtherRoles.ModUpdater.LaunchUpdater () [0x00012] in <16fd675636874a0ab113fe9c91bd63db>:0 
  at TheOtherRoles.ModUpdaterButton.Prefix (MainMenuManager __instance) [0x0000d] in <16fd675636874a0ab113fe9c91bd63db>:0 
  at (wrapper dynamic-method) MainMenuManager.DMD<MainMenuManager::Start>(MainMenuManager)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.(il2cpp -> managed) Start(intptr,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)
 game crashes on main menu with blackscreen

**Comment by Eisbison** [comment]
Why are you using the reactor fork of bepinex? :) That's not what the mod uses/is build on. It's not supposed to work with that.

**Comment by MrFawkes1337** [comment]
> Why are you using the reactor fork of bepinex? :) That's not what the mod uses/is build on. It's not supposed to work with that.

My mod is built on the latest fork, hence the install. I just thought you hadn't updated the folder, nevermind haha. Closing

**Comment by amsyarasyiq** [comment]
use this one https://github.com/NuclearPowered/BepInEx/releases/tag/6.0.0-reactor.23

**Comment by MrFawkes1337** [comment]
Old, but at the time it was 6.0.0-reactor21 that was the latest. Besides, ToR is built on the BE builds.
