### ISSUE TITLE
Stuck after meetings

### ISSUE THREAD

**Issue by Scamper10** [Eisbison/TheOtherRoles#162]
After a meeting, I have about a 75% chance to get stuck on the "Player was ejected" screen.
Sometimes another meeting fixes it, sometimes it doesn't.
This is a vanilla among us bug (I think) but I have found it to be much more common with TheOtherRoles.

**Comment by EoF-1141** [comment]
I cannot reproduce this at all.
And also never seen this issue on a stream or anywhere before. 
Are you sure this is related to TOR?

**Comment by Scamper10** [comment]
That's odd, it happens very consistently to me and other devices on my network.

**Comment by Scamper10** [comment]
If it doesn't happen on other devices what do **I** do to fix it?

**Comment by amsyarasyiq** [comment]
vanilla bug
