### ISSUE TITLE
Air Ship stairs v2.7.0

### ISSUE THREAD

**Issue by yfk2012** [Eisbison/TheOtherRoles#163]
Player 1 is in the process of climbing stairs
From the perspective of other players, Player 1 did not climb the stairs and always stood in front of the stairs
v2.7.0

**Comment by MrFawkes1337** [comment]
Try v2.7.1 and see if it’s still happening. I don’t have this issue at all.

**Comment by yfk2012** [comment]
It is a pity that this problem still occurs in v2.7.1
There is only test file in the compressed file
But after the game is launched for the first time, the mod will download 371 pictures about the cap
But does not load the hat file
The number of user files varies between the first startup and multiple startups
Will cause the problem of climbing stairs

**Comment by yfk2012** [comment]
![F5(F)_LFFW)OZ$MRW`SY9NR](https://user-images.githubusercontent.com/53398439/122808317-5507cc80-d2ff-11eb-9deb-b754c5f41f1d.png)

**Comment by yfk2012** [comment]
If the game does not have the TheOtherHats folder, it will become that no one can climb the stairs 
And stuck forever
![VQ1$CB1}9F$_NZ4(0%}OU)K](https://user-images.githubusercontent.com/53398439/122941059-9c499800-d3a7-11eb-9ff1-020e2e946b13.png)

**Comment by MrFawkes1337** [comment]
> It is a pity that this problem still occurs in v2.7.1
> There is only test file in the compressed file
> But after the game is launched for the first time, the mod will download 371 pictures about the cap
> But does not load the hat file
> The number of user files varies between the first startup and multiple startups
> Will cause the problem of climbing stairs

@Eisbison I think this can be fixed by initially bundling a zip including hats, instead of having the initial download, or if you decide the download is a good route, add instructions on the readme for people to restart the game once after initially loading, so that CustomHats can be initialised again, and load from the folder properly.

**Comment by Maryjane007** [comment]
You call these ladders not stairs
