### ISSUE TITLE
Mehrfache Rollenvergabe

### ISSUE THREAD

**Issue by fre4kyC0de** [Eisbison/TheOtherRoles#164]
Ein Vorschlag:
Könnte man eine Option hinzufügen, um eine mehrfache Vergabe von Rollen zu gestatten (z.B. 2x Engineer, ...)? Das würde ein Ausschlussverfahren nach "A ist Engineer, B muss Imposter/Jackal sein" verhindern und dem Spiel einen anderen Drall verpassen.
Bei einzelnen Rollen wie z.B. Jackal müsste man jedoch überlegen, ob man diese ausschließt.

Viele Grüße

**Comment by EoF-1141** [comment]
This would require an entire codebase rework and is not planned.
