### ISSUE TITLE
Incorrect Color-types for new Colors

### ISSUE THREAD

**Issue by anionDev** [Eisbison/TheOtherRoles#165]
Hey everyone!

We just found a new bug for the hacker & detective roles. All the new colors (marked as "New in 2.7.0" and "New Innersloth Colors" in the graphic) are shown as darker colors, doesn't matter if they are dark or light. Can be reproduced every game.

**Comment by EoF-1141** [comment]
Known
Already fixed on the Dev repo

**Comment by JerryGreen** [comment]
BetterCrewLink (https://github.com/OhMyGuus/BetterCrewLink) shows off some of the TheOtherRoles colors as "red". I guess those two problems are related
