### ISSUE TITLE
[Oversight] The Bounty Hunter is missing on the Images/TOR_roles.jpg

### ISSUE THREAD

**Issue by Benio101** [Eisbison/TheOtherRoles#167]
**The Issue**
The **Bounty Hunter** is missing on the [Images/TOR_roles.jpg](https://github.com/Eisbison/TheOtherRoles/blob/main/Images/TOR_roles.jpg).

**How to Fix**
Add the **Bounty Hunter** image to the [Images/TOR_roles.jpg](https://github.com/Eisbison/TheOtherRoles/blob/main/Images/TOR_roles.jpg).

**Comment by dwd0tcom** [comment]
Thank you! It'll be fixed in V2.9.0!
