### ISSUE TITLE
[Regression] The quality of the Images/TOR_roles.jpg is very low

### ISSUE THREAD

**Issue by Benio101** [Eisbison/TheOtherRoles#168]
**The Issue**
The quality of the [Images/TOR_roles.jpg](https://github.com/Eisbison/TheOtherRoles/blob/main/Images/TOR_roles.jpg) is very low.

- Resolution of a single role image of the [Images/TOR_roles.jpg](https://github.com/Eisbison/TheOtherRoles/blob/v2.6.3/Images/Preview_2.6.0.png) between [2.6.0](https://github.com/Eisbison/TheOtherRoles/tree/v2.6.0) and [2.6.3](https://github.com/Eisbison/TheOtherRoles/tree/v2.6.3): 1000×563 px
- Resolution of a single role image of the current [Images/TOR_roles.jpg](https://github.com/Eisbison/TheOtherRoles/blob/main/Images/TOR_roles.jpg): 240×135 <sup>1</sup>/<sub>7</sub> px

**Example**
Warlock image is taken from the [2.6.3](https://github.com/Eisbison/TheOtherRoles/tree/v2.6.3), while Bad Mini image comes from the current version.

![21 06 28 01꞉49꞉30](https://user-images.githubusercontent.com/7223948/123632736-9117c180-d818-11eb-98ba-0f6d44281a08.png)![21 06 28 01꞉49꞉48](https://user-images.githubusercontent.com/7223948/123632739-91b05800-d818-11eb-87ed-6b7108f2d649.png)

**How to Fix**
Increase the resolution of the [Images/TOR_roles.jpg](https://github.com/Eisbison/TheOtherRoles/blob/main/Images/TOR_roles.jpg).

**Comment by Maryjane007** [comment]
Well the 2nd image is fake, because the role is called evil mni and not bad mini

**Comment by Benio101** [comment]
> Well the 2nd image is fake, because the role is called evil mni and not bad mini

This is the image from the [`main`](https://github.com/Eisbison/TheOtherRoles/tree/main) branch, available on top of [README.md](https://github.com/Eisbison/TheOtherRoles/blob/main/README.md) of [https://github.com/Eisbison/TheOtherRoles](https://github.com/Eisbison/TheOtherRoles)…

**Comment by Maryjane007** [comment]
Ok, my fault

**Comment by dwd0tcom** [comment]
Fixed this also in V.2.9.0. Thank you!
