### ISSUE TITLE
No Issue, A new Role idea

### ISSUE THREAD

**Issue by itsoskurr** [Eisbison/TheOtherRoles#171]
_**Maniac**_
**_Impostor-Role
Kill-Cooldown (40)_**

Special Ability:
In The first round, he will be Crewmate-Maniac (at this time he can get guessed as Crewmate and Maniac)
but if he starts to kill it will change, like if he kills a medic he will become Medic-Maniac 
(at this time he can get guessed as Medic and Maniac)
And it will change on every kill, but if he kills a sheriff he will become Crewmate to avoid bugs.

**Comment by itsoskurr** [comment]
Sorry btw I didn't found where I can write ideas so here it is. <3

**Comment by Blackarchr** [comment]
On the TheOtherRoles Discord there is a category called Suggestions where you can create new role suggestions.
