### ISSUE TITLE
The latest v2021.6.30s officially supports Chinese Simplified and Traditional Chinese, please update?

### ISSUE THREAD

**Issue by xingxing2008** [Eisbison/TheOtherRoles#173]
like the title
最新v2021.6.30s正式支持了中文简体与繁体，麻烦更新下吗？
The latest v2021.6.30s officially supports Chinese Simplified and Traditional Chinese, please update?

**Comment by Maryjane007** [comment]
They will update, when they finish translating the mod and making it fit to Among Us 6.30

**Comment by EoF-1141** [comment]
I have uploaded a [2.7.2 Beta Release](https://github.com/Eisbison/TheOtherRoles/releases/tag/v2.7.2) which supports the latest Among Us Version.
However the full TOR Translation Update is not done yet (which will hopefully also add Chinese translations of TOR)

**Comment by Maryjane007** [comment]
@EoF-1141 Will you stream the translation process on Twitch??
