### ISSUE TITLE
[BUG] GUI Issues with new Among Us version

### ISSUE THREAD

**Issue by tom2208** [Eisbison/TheOtherRoles#174]
-all buttons including the garlic butten have a "kill" over it.
-The Arsonist cant see the crew in the bottom left corner.
-The bounty hunter cant see their bounty.
-no votes are shown

**Comment by EoF-1141** [comment]
TheOtherRoles v2.7.1 does not support Among Us v2021.6.30
Use the [v2.7.2 Beta](https://github.com/Eisbison/TheOtherRoles/releases/tag/v2.7.2) instead
