### ISSUE TITLE
stuck in the home screen

### ISSUE THREAD

**Issue by cinlul** [Eisbison/TheOtherRoles#175]
When I start the other roles, I'm stuck in the home sccreen.
The only button I can use is the 'exit'. The other buttons (like 'online'; 'local'; etc) are grey and I can't use them.
In the middle of the screen are the other roles lettering.
I did anything to fix that. I uninstall among us and the mod and install them again (multiple times) but it didn't work.
I try to ope n the mod with two different programms but  it was the same effect.
I'm a little bit frustrated and I realy need help. 
 Hope you can help me, thanks

**Comment by MrFawkes1337** [comment]
Make sure you have the steam_appid.txt in the base game folder, where you put Bepinex etc.

**Comment by amsyarasyiq** [comment]
Make sure you have Steam running in the background

**Comment by homeworkprod** [comment]
@cinlul I had the same issue, even with a fresh Among Us installation without any mods.

Switching to Proton 6.3-5 (from 5.x) did the trick for me.
