### ISSUE TITLE
Child Role Not Growing up

### ISSUE THREAD

**Issue by okyloky9** [Eisbison/TheOtherRoles#18]
Child has grown up to 18+ (no age shown, full body and not small) and still ends game. Has happened on multiple occasions.

**Comment by Eisbison** [comment]
Voted out or killed?

**Comment by Eisbison** [comment]
Closing the issue because the hotfix update today fixes this anyways

**Comment by okyloky9** [comment]
Sorry I didn't check my notifs, both voting and killed did it but the fix did indeed work!
