### ISSUE TITLE
Severe Lag / frame drops when Camouflage is on

### ISSUE THREAD

**Issue by jmaximusix** [Eisbison/TheOtherRoles#183]
In the latest version we (entire lobby) experienced some severe lag / frame drops occuring while camouflage was on.
Since I directly updated from version 2.7.0 to 2.73 I don't know where exactly this bug was introduced, but it seems like it must have been one of the versions since 2.7.0. Hope this gets fixed soon, because we had to turn off the camouflager role because of this

**Comment by christian94M** [comment]
v2.8.1 has the bug too. See

**Comment by Eisbison** [comment]
Fixed with v2.9.2
