### ISSUE TITLE
[ROLE SUGGESTIONS]

### ISSUE THREAD

**Issue by JayrenCekiss** [Eisbison/TheOtherRoles#184]
Paladin Role:
Once per round can use Detect Evil. 30% chance to uncover an imposter. Every kill the % goes up to a maximum of 50%.

Night Watchman Role:
Flashlight: Can use a flashlight during lights off to see. 50 second cool down.

Once per round: Can access cameras no matter where at on the map.

Praetorian Guard/Bodyguard Role:
Choose a player to guard. If they get killed you die instead.

Necromancer Role:
Once per game can reanimate a dead player and turn them into a standard impostor. If the reanimated impostor is killed by a sheriff the Necromancer is revealed. If Necromancer dies their undead impostor dies too.

**Comment by Eisbison** [comment]
Please submit your role suggestions on our discord server :)
