### ISSUE TITLE
Shifter needs one more setting

### ISSUE THREAD

**Issue by Bayro97** [Eisbison/TheOtherRoles#19]
The shifter in this mod pack has the problem that he can shift several times the round. This makes it much too strong. I would like to have the possibility, like in Town of Us, to set the shifter so that he can only shift once per round and has to wait for a meeting.

**Comment by Phoenix616** [comment]
Alternatively there could be a separate cooldown for after meetings and after shifting for the new shifter?

**Comment by Eisbison** [comment]
I'm reworking the Shifter, things will be added/changed with the next update to make the Shifter viable.
