### ISSUE TITLE
Fix for Swapper dead vote screen

### ISSUE THREAD

**Issue by MrF1uff** [Eisbison/TheOtherRoles#190]
The new fix for if swapper is dead then dont swap is bugged. Now if the swapper is dead it does not show the votes. I found a fix for that
         {
                PlayerVoteArea swapped1 = null;
                    PlayerVoteArea swapped2 = null;
                    if (Swapper.swapper != null && !Swapper.swapper.Data.IsDead)
                        foreach (PlayerVoteArea playerVoteArea in __instance.playerStates) 
                    {
                        if (playerVoteArea.TargetPlayerId == Swapper.playerId1) swapped1 = playerVoteArea;
                        if (playerVoteArea.TargetPlayerId == Swapper.playerId2) swapped2 = playerVoteArea;

I just moved the if swapper is dead down 2 lines of code past the playervotearea swapped1 and 2 on both sections of code that have this and it fixed this problem. :D glad i could help

**Comment by MrF1uff** [comment]
i love tweaking with these mods and fixing minor bugs but thank you all for making them happen in the first place

**Comment by Eisbison** [comment]
Should be fixed with v2.8.0. Thanks for pointing it out.
