### ISSUE TITLE
Handling of PRs

### ISSUE THREAD

**Issue by soerface** [Eisbison/TheOtherRoles#192]
I saw that almost all pull requests are getting closed, not merged. However, some of the changes still end up in the mod by code being copied. Is there a reason why it is being done this way?

This is for multiple reasons irritating:
- As a new contributor, I scroll through the list of PRs and wonder why some are being rejected (they weren't, there was just not a single comment left and the changes were copied into the source)
- As a developer, I use `git blame` to see the reasons and thoughts of the author of a specific line. Since there is only a "version x.y.z" commit, I neither know who wrote something nor what the reason for that line was
- As a contributor, my name does not appear in the list of contributors on GitHub

I suggest adding a `CONTRIBUTING.md` file in the repository root: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors
This file will then be displayed when a new PR is made. Here, you can explain what criteria needs to be met so a PR can be merged.

**Comment by dwd0tcom** [comment]
We're working on a way to use the PRs better in the future. Since we're developing on a private repo it's kinda tricky to add PRs but we did this in the past and there might be a new way of better handling this in the future!
