### ISSUE TITLE
Cleaning the Bait's body results in body report without a body which exposes the reporting Impostor

### ISSUE THREAD

**Issue by Cybershadow81** [Eisbison/TheOtherRoles#197]
In a game we played today, we discovered the following problem:

One impostor killed the bait and the cleaner instantly cleaned the body which resulted in a body report without a body. The only logical explanation for a body report without a body is that the body got cleaned before the bait timeout forced the impostor to report which exposes the impostor and with a good chance also the cleaner to the crew without a chance to talk themselves out.

I would suggest implementing one of two solutions to that problem:

1) The bait's body cannot be cleaned.
2) Cleaning the bait's body prevents the forced self-report.

What do you think?

**Comment by gendelo3** [comment]
Can confirm, I think i have implemented a working fix in

#198 

(you can select 1. or 2.)
