### ISSUE TITLE
Mod Manager compatibility

### ISSUE THREAD

**Issue by MatuxGG** [Eisbison/TheOtherRoles#2]
Hello,

I'm Mod Manager's creator (https://github.com/MatuxGG/ModManager) and I really like your Mod.

I would really like to include it in my software for download (with credits and download from your github directly), to give you some visibility and allow people using this awesome mod easily.

However, Mod Manager requires you to make a valid release. To do so, your mod needs to be uploaded in the release section. Can you do it please ?

I did a fork of your project for now to allow compatibility and if you don't want me to provide your mod, I'll remove it on your demand. If you publish a correct release, I will use it instead too and remove my fork. For example, this is a valid submission : https://github.com/MatuxGG/TheOtherRoles/releases/tag/1.0. (You only need the .dll file in theory as Mod Manager provide latest BepInEx version to people but only the .zip or both works fine as well)

Thanks in advance,

Best regards ! :)

**Comment by Eisbison** [comment]
The new version should be a proper release you can use 👍

**Comment by MatuxGG** [comment]
Really cool from you, thanks ;)

**Comment by MatuxGG** [comment]
Oh BepInEx, mono, etc ... are not in root but in a directory TheOtherRoles inside the zip file. Is it possible to change it or to add the dll file aside please ? ^^

**Comment by Eisbison** [comment]
I think now we're done ;)
