### ISSUE TITLE
Role suggestion „Mirror“

### ISSUE THREAD

**Issue by fre4kyC0de** [Eisbison/TheOtherRoles#213]
I‘d like to suggest a new role, which works like a mirror.

The idea is, that this role can setup a shield (similar to the „Time Shield“), which will mirror attempts to kill him/her back to the Imposter/Jackal/… for a short amount of time. So if the shield is active, an Imposter/Jackal/… will kill himself/herself instead of the original target.

Possible options for the role would be
- the amount of time, the shield is active / the user has to wait for activation
- the report behaviour: no auto-report, make the „mirror“ report the (now dead) killer, make the (now dead) killer report himself/herself

**Comment by JeSuisUneLicorne** [comment]
We could name it "Cochie Man" 

https://www.youtube.com/watch?v=j_GTNBs80C4

Like this. Or we make him come back as a 4th killer party :)

**Comment by Eisbison** [comment]
Thank you for your suggestion, please put it in the discord server, as it's not really an issue and we're handling suggestions over there.
