### ISSUE TITLE
Die Rollenvergabe

### ISSUE THREAD

**Issue by Maryjane007** [Eisbison/TheOtherRoles#217]
Also es gibt Streamer und sonstige denen das passiert ist und zwar man kriegt die selbe Rolle vielmal hintereinander.
EIn Streamer namens Hahn, war 4 mal hintereinander Medic, ein weiterer Streamer namens Shantao war 4 mal hintereinander Bait und ich war mehrmals hintereinander Engineer.

Bitte fixt das, wenn es geht, Kuss geht raus <3

**Comment by Eisbison** [comment]
The roles are being distributed randomly... getting the same role 4 times in a row is just unlucky. There's no bug here, randomness just feels weird sometimes
