### ISSUE TITLE
Feedback: Gendered Language

### ISSUE THREAD

**Issue by IzzetJulie** [Eisbison/TheOtherRoles#224]
All of the role descriptions on your github page use he and him to describe players, which is not very considerate of your diverse player base. They or them for unknown players would be very much appreciated. Thank you!

**Comment by lacksfish** [comment]
That's such a non-issue it hurts my head actually. You literally signed up to Github to create _this_ issue?

Please take your virtue-signaling to another repository.
The developers worked really hard on this mod, so please don't come in here and accuse them of misogyny.
