### ISSUE TITLE
Suggestion: Hardcore options

### ISSUE THREAD

**Issue by bothie** [Eisbison/TheOtherRoles#227]
Some hardcore options I suggest:
* Any eject of a crewmate triggers an instant win of the evil roles (i.e. cremates are not allowed to vote out an innocent player).
** Sub-Option: Shifter counts as evil/innocent player
* On a tie, all players (with hightest vote count) are ejected. (Should all remaining players get voted out this way, the last standing evil roles win).
* If one killing role didn't kill this round, her first kill in next round has a 50% chance to act as a bait kill. Also, if the killing role didn't kill for n rounds, the next n kills have that bait-chance. If one of the kills hits an actual bait, the kill after that will have the bait acting chance instead. Example: round 1+2: no kill. round 3: bait-kill. round 4: no kill. round 5: two kills (both have 50% chance to act like bait kill). round 6: two kills (the first one still has a 50% chance to act like a bait kill, the other one turns back to being normal). round 7: someone is not doing his job ;)

**Comment by Eisbison** [comment]
Thank you for you're suggestion. Please move your suggestion to our discord server, where we usually handle them, as they are not actually issues.
