### ISSUE TITLE
Garlic always available even without vampires

### ISSUE THREAD

**Issue by Camusensei** [Eisbison/TheOtherRoles#229]
If the vampire probability is set to 0% and the option "Vampire Can Kill Near Garlics" is off (default), crewmates should not have a "garlic" available.

When people with the mod join a non-modded game, they should not have garlic available.

**Comment by dwd0tcom** [comment]
But why should people with the mod, join a non-modded game?

**Comment by Camusensei** [comment]
I always have the mod installed, which is useful for changing the map and the number of impostors even when other people do not have it. It's also helpful to have the amount of remaining tasks.
I'm not saying it's a good reason but it's at least one ^^
But this bug is slightly annoying when I'm not the host or when I forget to change the default for garlic which is why I reported it.

**Comment by Eisbison** [comment]
You don't have a Garlic, when the vampire probability is 0. Also you shouldn't join public lobbies when you have the mod installed.

**Comment by Camusensei** [comment]
Hello @Eisbison. That is not true. Or at least it was not and maybe something changed since then. You should read the bug report thoroughly and not select the part of my justification as a reason to unjustly dismiss this case. And I only join private lobbies, don't start assuming false things.
