### ISSUE TITLE
[Suggestion] Option to make Spy be red for impostors after sidekicked.

### ISSUE THREAD

**Issue by Quarris** [Eisbison/TheOtherRoles#230]
Currently Jackal doesn't know if they sidekicked impostors or not, I think it would be a good option to make it so that impostors don't know if the spy got sidekicked. Sidekicking the spy sends an instant target on them by the impostor, and makes the role irrelevant as the impostors now know who their partners are.

**Comment by Floris0106** [comment]
I think it would be a better idea if the spy cannot get sidekicked, but the jackal does see as if the spy got sidekicked (similar to how sidekicking imposters works). This way the spy can also spy on the jackal if they get sidekicked.

**Comment by dwd0tcom** [comment]
This is a nice idea, we'll look into it!
