### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by PiccoloZ** [Eisbison/TheOtherRoles#232]
Added skill cooldowns setting at the beginning of the game
Hackers can view the heartbeat detector from anywhere
Evil mini can't be killed by gusser before they grow up
Nice mini grow up to be sheriff after the next meeting
After the electricity is destroyed, the lighter can share his vision with those around him
The number of maintenance times for engineers in each game can be set
Arsonists can use the vents

NEW ROLE
Injector is a impostor who can inject narcotics into other players，the target player reverses direction after the next meeting, lasting one round.

**Comment by dwd0tcom** [comment]
Hey @PiccoloZ, feel free to submit those Ideas to our Discord. We got a dedicated channel just for ideas!
https://discord.gg/9vwraAGS
