### ISSUE TITLE
It can't use in 2021.11.9.5e

### ISSUE THREAD

**Issue by 666233j** [Eisbison/TheOtherRoles#235]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type GameSettingMenu and name OnEnable and parameters 
[Error  :   BepInEx] Error loading [The Other Roles 2.9.2] : Patching exception in method null

**Comment by dwd0tcom** [comment]
That's because the mod is not supported yet by this version of Among Us.
