### ISSUE TITLE
Support for Among Us Version v2021.11.9.5s

### ISSUE THREAD

**Issue by 1nVitr0** [Eisbison/TheOtherRoles#236]
I presume the release of the new Among us Version has changed a lot of things. First and foremost with roles now integrated into the base game, this might expose a new and better pathway to implement this repository's roles. It probably also takes some time to resolve conflicts between the new roles in the base game and the additions from TheOtherRoles.

I am happy to help, as are many others I'm sure. But before I dive head first into the code and implement things, I would like to collect some research first. Especially the thoughts of @Eisbison as the maintainer of the project matter here, before we bring chaos into his codebase and do work that he or others have already done.

*Also, @Eisbison  feel free to close and reopen this issue if you need more control over the original thread.*

**Comment by dwd0tcom** [comment]
Done.
