### ISSUE TITLE
3.1.0 Release Package seems to be the same 3.0.0

### ISSUE THREAD

**Issue by basarama** [Eisbison/TheOtherRoles#239]
Tried downloading the release TheOtherRoles.zip from the 3.1.0 release but after following setup instructions it's still 3.0.0 at the main screen and none of the new options for medic sees kill attempt, etc show up. Also still banned in lobbies for hacking.

**Comment by ministerpl** [comment]
same

**Comment by dwd0tcom** [comment]
This should be fixed by now.
