### ISSUE TITLE
Votes inaccurate

### ISSUE THREAD

**Issue by itsjennii** [Eisbison/TheOtherRoles#24]
We had the problem in our games, that when someone voted someone, the vote went to another person and not actually the person they voted. 

For example, if I voted myself, I didn't have a vote on myself at all but another person got my vote and this happened several times in different games and different lobbies.

**Comment by Eisbison** [comment]
Are you sure that it isn't just the normal among us voting bug where if you click on the left side, a person on the right side is being selected?

**Comment by itsjennii** [comment]
> Are you sure that it isn't just the normal among us voting bug where if you click on the left side, a person on the right side is being selected?

AHHHH, yeah you're right it's that bug. Didn't even know that was a thing, I'm sorry! Thank you for your response :)
