### ISSUE TITLE
Medium ghost questing game breaking bug

### ISSUE THREAD

**Issue by Eniplay** [Eisbison/TheOtherRoles#248]
I had a bug after asking a dead person. 
In the chat Message was a .xml tag with the exact color of the killer in hex code. (see attached Image)  
![image](https://user-images.githubusercontent.com/10630916/143658291-812cdfa4-165d-44e6-b88b-ed055aa927c4.png)

**Comment by Eisbison** [comment]
I'd say game-breaking is something different, but we fixed it
