### ISSUE TITLE
Winning condition Jackal + Sidekick + Lawyer seems bugued

### ISSUE THREAD

**Issue by Thibault-Brocheton** [Eisbison/TheOtherRoles#249]
We played  a game, I was the Jackal, I had a sidekick and a Lawyer on me.
When we won the game, I wasn't considered winning.

I didn't try to reproduce it, don't know if it was a random issue or not. 

![Capture](https://user-images.githubusercontent.com/7646137/143726812-67200105-c124-40be-90cf-0a9d72a3c265.JPG)

**Comment by Eisbison** [comment]
Please read through the win conditions again.The Lawyer steals the win of the client, if they're both alive. The second member of team jackal wins tho.
