### ISSUE TITLE
Seeing through camo

### ISSUE THREAD

**Issue by TokyoAxel** [Eisbison/TheOtherRoles#25]
for some reason, almost every time we've played, 1 person can see through the camo. It keeps leading to people just watching the imposter kill and not knowing that we werent supposed to be able to see colour.

**Comment by Eisbison** [comment]
Weird, but you are not the first with this issue, I'll look into it

**Comment by Eisbison** [comment]
A hotfix is coming in a few hours, it should fix this issue. If not, please reopen the issue 😉
