### ISSUE TITLE
Vampire teleports to Victim after Kill

### ISSUE THREAD

**Issue by fsamiec** [Eisbison/TheOtherRoles#253]
After the victim of the Vampire gets killed, the imposter will be ported to the victim.

**Comment by amsyarasyiq** [comment]
Doesn't the v3.2.3 fixed this?

**Comment by Eisbison** [comment]
No it doesn't, I messed up xD Before 3.2.3 the bug appeared casually, hence I kind of rewrote things to avoid that but forgot to use the roght function call in the end xD It's just one param missing, I'll release it todax or tomorrow, just wanted to wait if there is something else to hotfix xD
