### ISSUE TITLE
Lawyer can win when shot by guesser

### ISSUE THREAD

**Issue by kezsulap** [Eisbison/TheOtherRoles#255]
![Screenshot from 2021-12-05 15-21-02](https://user-images.githubusercontent.com/16389252/144750537-70be43e4-6b37-4f24-b909-1f8bb21c988d.png)
![Screenshot from 2021-12-05 15-22-14](https://user-images.githubusercontent.com/16389252/144750539-02160f44-df9c-4651-8703-b8fbb4a02276.png)
I'm not sure if it's a bug or intended behaviour, but even if I feel it needs at least some clarification in the rules.
We had 3 people alive: Evil Guesser, Lawyer and some Crewmate, the Guesser correctly guessed Lawyers role and the game ended but called Lawyer's win.

**Comment by Eisbison** [comment]
Well the role description covers this case (so there is some clarification), this behaviour is intended :) So I'll close the issue.
