### ISSUE TITLE
it has some bug in ending screen.

### ISSUE THREAD

**Issue by inside2e** [Eisbison/TheOtherRoles#256]
![bug1](https://user-images.githubusercontent.com/58885124/144867207-39e74555-5ad2-47d2-824b-1519e5d79b45.jpg)
Look. Crewmate is winning by voting all the Jackal and impostor but why the Vulture and Jackal can win together?

**Comment by dwd0tcom** [comment]
It seems like, this is a fork and not our release. We did not implement any other language. Please refer to the fork.
