### ISSUE TITLE
Problem Among us other roles mod

### ISSUE THREAD

**Issue by Lyrixxhermes** [Eisbison/TheOtherRoles#26]
Hello dear GitHub team. For several days I have been trying to install the other roles mod or generally Among us mods. But even though I follow all the steps correctly and everything is correct, it never works for Trzdm. With the otheroles mod should be above that the otheroles mod is installed but despite all mods this is just the normal one among us and I don't have the chance to get other roles because it just doesn't work. So I wanted to ask if you could help me: D lg.Niclas

**Comment by Eisbison** [comment]
Did you install the vcredist listed on the github page?
