### ISSUE TITLE
Can I use configuration files for text content?

### ISSUE THREAD

**Issue by xibok** [Eisbison/TheOtherRoles#267]
Can I use configuration files for text content?
I hope to be able to do localized translation

**Comment by dwd0tcom** [comment]
Which files do you mean?

**Comment by xibok** [comment]
> Which files do you mean?

Mainly setting

**Comment by xibok** [comment]
I mean to change the configuration text to read the content of the file

I have tried to modify the source code and then compile, but my environment configuration keeps failing

**Comment by dwd0tcom** [comment]
You can do whatever you like. No need to ask here
