### ISSUE TITLE
Morphling vent

### ISSUE THREAD

**Issue by FerbFloo** [Eisbison/TheOtherRoles#27]
This is not an issue i have with the mod (i really love it, can't play vanilla anymore xD), but more a suggestion: Would it be possible to add a setting for the Morphling, which prevents him to vent while disguised? This would force him to think ahead and plan his kills better, instead of just running into a group of people as morph, killing one and venting away (which happens way too often imo)

And while I'm at it: Would it be possible to nerf the Seer, so he can only see the names of the people he already used his ability on during camouflage, instead of all of them? (Or also make it a setting)

**Comment by Eisbison** [comment]
Please write such things in the Discord feature-suggestion channel, those are not issues ;)
