### ISSUE TITLE
If Jackal makes Impostor to a Sidekick, the Impostor team should not know that his teammates have defected. (Evil Guesser can easily guess the identity of Sidekick)

### ISSUE THREAD

**Issue by CoolLKKPS** [Eisbison/TheOtherRoles#271]
If Jackal makes Impostor to a Sidekick, the Impostor team should not know that his teammates have defected (Evil Guesser can easily guess the identity of Sidekick), the red names of Impostor teammates will not be updated, and the Impostor who becomes Sidekick can still see who his previous teammates are.
But if the normal Impostor has been in contact with the Impostor who became Sidekick for a long time (Configurable), the normal Impostor will update the color of the name of the traitorous teammate.

**Comment by JustASysAdmin** [comment]
We just play with that setting off honestly.
