### ISSUE TITLE
[Suggestion] New Roles

### ISSUE THREAD

**Issue by CoolLKKPS** [Eisbison/TheOtherRoles#272]
1. Saboteur (Impostor)
Saboteur can force everyone to skip the vote (configurable number of times), but it will cause Saboteur to be unable to kill before the next meeting begins.
Saboteur has a passive ability. When it is ejected, it can still survive until the next meeting begins. Saboteur can transfer the passive ability to others no matter who he is or where he is.
2. Lurker (Neutral)
Lurker can be invisible for a while, but Lurker cannot kill anyone.
The goal of Lurker is to identify the identities of all surviving players. Lurker will know all the identities that have been distributed from the beginning. If Lurker fails to identify a player or a same player more than a certain number of times (Configurable), Lurker will die directly; If Lurker identifies a player’s identity is correct , Lurker must wait for the next meeting to start before continuing to identify.

**Comment by dwd0tcom** [comment]
The Saboteur might be too OP, if your mate is still in-game.
