### ISSUE TITLE
[Suggestion] Lawyer and Pursuer

### ISSUE THREAD

**Issue by CoolLKKPS** [Eisbison/TheOtherRoles#273]
The target player of Lawyer can be anyone and not a specific team. The Lawyer must help the target player to win together. If Lawyer fail to protect the target player, Lawyer will become Pursuer.
Pursuer needs to be more aware of the team of the target player, because when the team of the target player is not a neutral team other than the Jackal team, the victory conditions are the same as Lawyer, otherwise Pursuer must survive to the end.
Note: Lawyer cannot know the identity of the target; Pursuer cannot do the task; Lawyer can be configured to not know who its target is, and if the target does not know that he is the target too, Lawyer's identity color will be shown to everyone but not the specific identity.
Why suggest that: The frequency of Lawyer and Pursuer winning is too high, because the winning conditions are too simple and easy, which affects the balance, personally feel that it does not even match the Lawyer concept.

**Comment by dwd0tcom** [comment]
Can you give some more information about how we should balance it?

**Comment by CoolLKKPS** [comment]
Sure, because the winning conditions of this role are actually really easy. It can win together with their client; let their client dies or gets voted out and win the victory together with the crewmate or the impostor, or win the victory by call the meeting, or steal their client victory.
I can even know that my client is not a crewmate, this role must balance the winning conditions, and the lawyer’s client will not necessarily be a crewmate.

**Comment by CoolLKKPS** [comment]
**Is your feature request related to a problem? Please describe.**
Victory conditions are too easy.
**Describe the solution / role you'd like**
Changed to a gameplay similar to that of a crush.
**Describe alternatives you've considered**
Turn off "Lawyer Wins After Meetings" and nerf "Lawyer Vision" but still not balanced enough.
**Additional context**
I think the original intention of this Role is that the lawyer can always hide his identity and try not easily to let others know it from the beginning, but now when u know u are a target, I only need just watch someone dancing next to me, and then know who the lawyer or medic is.

**Comment by dwd0tcom** [comment]
We need to discuss this in our team again. Thanks for the input!
