### ISSUE TITLE
Guesser Icon rendered behind mask

### ISSUE THREAD

**Issue by marcoSchr** [Eisbison/TheOtherRoles#275]
# Expected behavior:

The guesser Icon is rendered in front of all cosmetic options

# Observed behavior:

The guesser Icon is rendered behind face accessories.

# Steps to reproduce:

- Have an other player with a face cosmetic option
- be guesser

# System Information:

    Arch Linux
    Steam Proton 6.3-8
    Among Us 2021.12.15s (build 1421)
    The Other Roles 3.3.3

# Example
![Screenshot_20211221_212524](https://user-images.githubusercontent.com/49691247/147005873-f1d2d9c5-b562-42a5-8b83-2a34ff6416ed.png)

**Comment by dwd0tcom** [comment]
Wow 🤩 what a nice report!
I saw this some days ago and fixed it yesterday. The fix will be in the next release. Thanks for your report 🙌
