### ISSUE TITLE
[Suggestion] Hide and Seek and Submerged

### ISSUE THREAD

**Issue by AvgZing** [Eisbison/TheOtherRoles#277]
This is better than polus.gg in almost every way, EXCEPT that it's missing the Hide And Seek gamerule, as well as the Submerged map.

**Comment by Maryversal** [comment]
The Submerged map cannot get into the mod because it is a mod itself and the devs do not allow it to get into any other projects. The hide and seek gamerule, you dont need, because, you can make a preset for it :)

**Comment by dwd0tcom** [comment]
Submerged is server-side, which makes it hard for us to implement it. For Hide and Seek, just ask your lobby, if you wanna play this mode.
