### ISSUE TITLE
[Suggestion] Make revealed snitch unguessable in meetings and/or reveal imposters in meetings 

### ISSUE THREAD

**Issue by Oshroth** [Eisbison/TheOtherRoles#278]
Currently it makes it extremely difficult to succeed as Snitch as you need to do all of your tasks, see the imposters without them killing you or calling a sabotage and get to the meeting room to call a button, then say who the imposter is before they guess you.

**Comment by Maryversal** [comment]
I like that idea :)

**Comment by Oshroth** [comment]
There's an unmerged PR that added a setting for making revealed snitches unguessable. #194

**Comment by dwd0tcom** [comment]
Yes, but it has conflicts, I'll resolve them and see if there is any bug. Thanks!
