### ISSUE TITLE
[Bug Report] Witch curse triggers before non-witch imposter is ejected

### ISSUE THREAD

**Issue by Oshroth** [Eisbison/TheOtherRoles#279]
**Describe the bug**
I had a game where there was 5 players remaining (2 imposters) and one player was cursed by witch. We voted out the non-witch imposter but the game ended as a win for the imposter team during the ejection screen even though the win screen showed the ejected player as dead.

**Expected behavior**
The game should have continued after the meeting with the witch and two other players remaining. 

**System (please complete the following information):**
 - OS: Windows 10
 - Among Us Version v2021.12.15s
 - TheOtherRoles Version v3.3.3

**Additional context**
It seems like the TOR does the witch curse calculation before the ejected player is counted as removed from the game. e.g. (Witch not voted. Kill cursed player) -> (2v2 = imposters win) -> (Imposter ejected) -> (display win screen)

**Comment by dwd0tcom** [comment]
Thanks for your report! We put this on our backlog and we'll fix this!

**Comment by Mallaris** [comment]
should be fixed, if the problem should occur again please contact us again
