### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by SiberianNova** [Eisbison/TheOtherRoles#280]
can open the game with the mods on, but can't start or host a game. get the message; "You disconnected from the server. Reliable packet 1 (size = 40) was not ack'd after 7500ms (9 resends)"

I have also tried other Mod Versions as well same error.

**Comment by dwd0tcom** [comment]
So this bug has nothing to do with the mod itself, it's a vanilla AU bug. Try a complete reinstall.

**Comment by SiberianNova** [comment]
So the actual problem was that when the game first opened with the mod, the Server for the location was set to "Custom" it needed to be changed back to "North America" and it worked with no problem. Might want to add that to the list of things to do when first downloading the mod.

Thanks for the help.
