### ISSUE TITLE
[Suggestion] Change Engineer's Repair button color from red to blue

### ISSUE THREAD

**Issue by DracoL1ch** [Eisbison/TheOtherRoles#282]
Reddish Repair button seems quite a lot like a report button. It may be bad for quick-reaction misclicks.
Changing background from red to whatever not-red would fix it instantly.

**Comment by dwd0tcom** [comment]
Seems like a good improvement to me! Thanks!

**Comment by dwd0tcom** [comment]
Done! Thanks for your contribution!
