### ISSUE TITLE
[Suggestion] Auto-complete quests for players with 5mins+ death time

### ISSUE THREAD

**Issue by DracoL1ch** [Eisbison/TheOtherRoles#283]
Sometimes player dies first and stands off his PC for quite a while, letting the game go. If there are no active killing, he may end up being the only one with no quests.
If it's not a big issue, there can be a timer to track those AFKs with next to 0 quests, to automatically complete all their tasks if 5 mins passed (except voting time) since their death.

**Comment by JustASysAdmin** [comment]
If this was implemented half of our games would be a task win.

Keep in mind while this has a niche use, it's also a hard timer, which arsonist already does.

**Comment by dwd0tcom** [comment]
If a player seems to be afk and the crew can't win, simply vote-kick them. If we would implement auto-complete for tasks, it would be way too op.

**Comment by DracoL1ch** [comment]
but the issue is, you can't kick unless you're calling a meeting, and thats not always an option, not to speak you have to interfere game as a ghost to tell ppl there are afk'ers
