### ISSUE TITLE
[Suggestion] Another deputy promote option

### ISSUE THREAD

**Issue by DracoL1ch** [Eisbison/TheOtherRoles#288]
Problem : sheriff has no idea who to kill the very first round. And he May end up dying with no impact whatsoever. 
 If a deputy strait forward promotes into a sheriff After sheriff done his things and died, that become too harsh for imps to survive. 

Instead, I'd Like to Suggest another option - only promotes if sheriff dies before the first meeting. 

This way crew wont have too much power for double checking, and sheriff wont die in vain while having no info before the first meeting.

**Comment by JustASysAdmin** [comment]
Um.....I'm just a lowly player and all but.....isn't the solution to your problem to not RDM as sheriff?

**Comment by gendelo3** [comment]
There is the much more frequent scenario, in which the sheriff is killed by an impostor or jackal, in the first round.

One solution that would exclude RNG is that the deputy only promotes if the sheriff was killed (by another player) before the first meeting, but that is not only complicated, it would also give more info about the cause of the sheriff's death to the deputy.

I think a general deputy promotes "if sheriff died before the first meeting" is better. However, I don't know if it is really worth the effort to implement it.
