### ISSUE TITLE
Left text gets cut

### ISSUE THREAD

**Issue by 1upCAD** [Eisbison/TheOtherRoles#29]
Text on the left is cut off when using the following resolution: 1680x1050

![image](https://user-images.githubusercontent.com/76631475/112086003-7a970580-8b59-11eb-9c2f-eef19b42f25b.png)

Can this be updated to make sure the text doesn't get cut off?

Thanks.

**Comment by 1upCAD** [comment]
> I had the same issue, it seems like the text is rendered in relation to your screen. If you have a lower screen resolution set in game than your screen, it gets cut off.

My screen resolution in game, is the same as the resolution set in Windows. So that's not the issue. This issue appeared in the 1.6 release and is still there in 1.7, but it was not an issue in 1.5 or earlier.

**Comment by Eisbison** [comment]
I'll address this, when the next Among Us version comes out.
