### ISSUE TITLE
(suggestion)New role Cult leader & cultist

### ISSUE THREAD

**Issue by Pawel99UK** [Eisbison/TheOtherRoles#297]
a new neutral killer role the cult leader he job is to kill everyone one using other player to join his way off life.he has a new ability the shrine button (what it does is that it place a shrine where your standing and when a person step on the shrine they become a cultist)the cultist has to help the cult leader win all do he does not have the vent power like the leader.

role color blue-purple 

Additional content/settings
make the shrine inv on/off
amount of player affected default 1
jester can become effected (off/on)
impostors can become effected (off/on)
jackal can become effected (off/on)

**Comment by Mallaris** [comment]
if you have a suggestion please submit it on our discord :)
