### ISSUE TITLE
Showing 2 mod versions on main screen

### ISSUE THREAD

**Issue by Ducky369** [Eisbison/TheOtherRoles#30]
Hello, 

After downloading v 1.6, I experienced an error where on the main screen of AmongUs it shows that I have both version 1.4 and 1.6. I have completely uninstalled AmongUs and reinstalled it and I have tried with a fresh download of the v 1.6 update and I still have the same issue. I just saw that there is now a version 1.7 and unfortunately it is having the same problem for me. It shows that I have version 1.4 and 1.7 running. I did previously have version 1.4, but had no issues when I updated to 1.5. I have no files containing 1.4 on my computer anywhere.  This causes in-game errors such as not being able to see the shield a medic has put around me to protect me, not being able to see roles as the seer, and more. Here's a screenshot of the error. 
<img width="960" alt="1 4 and 1 7 error" src="https://user-images.githubusercontent.com/81264803/112216766-829d8680-8be7-11eb-9902-15243785b430.png">

Here's what my folder looks like with the mod in it: 
<img width="609" alt="1 7 error" src="https://user-images.githubusercontent.com/81264803/112216952-b9739c80-8be7-11eb-93c5-3e15a44219a8.png">

Thanks in advance!

**Comment by FerbFloo** [comment]
Yeah, it sometimes does that when installing a newer version of the mod on top of an older one. Just take your vanilla files and add only the newest files from OtherRoles to them to fix that problem...

**Comment by Ducky369** [comment]
> Yeah, it sometimes does that when installing a newer version of the mod on top of an older one. Just take your vanilla files and add only the newest files from OtherRoles to them to fix that problem...

Ya, that's what I've done and its still not working.

**Comment by Eisbison** [comment]
Clear all the data, also the temporary one. Then you should be good to go.Fresh among us install fresh mod install.
