### ISSUE TITLE
[Bug Report] [Original] Vent stuck

### ISSUE THREAD

**Issue by DracoL1ch** [Eisbison/TheOtherRoles#308]
There's an known bug with vents on Polus' laboratory vents, when you able to click Vent before being close to it and then unit stucks.
https://www.youtube.com/watch?v=--s9Yt7HskY

Is it possible to make a workaround for that? I can imagine a couple of approaches:
1. Reduce the range where 'vent' button triggers for this particular vent;
2. Start a timer for each vent-jump attempt and check periodically if unit's coordinate hasn't changed for 1-2 seconds and unit is NOT hidden; then unstuck (cancel vent order?);

This bug ruined quite some games and original devs seems to ignore that

**Comment by K3ndoo** [comment]
We tried to fix this a long time ago. "original devs seems to ignore that" That's just a lie.

Easy fix: Walk closer to the vent/Stop trying to vent too early.

**Comment by DracoL1ch** [comment]
'original' means innersloth and since it wasnt addressed for more than 1.5 years I can definitely use the word "ignore".
of course im aware of how to avoid it, yet it's still a bug, thanks for ur incredibly valuable hint

**Comment by K3ndoo** [comment]
Innersloth already fixed this vent bug. It's only existing in ToR, not in Vanilla.

**Comment by DracoL1ch** [comment]
> Innersloth already fixed this vent bug. It's only existing in ToR, not in Vanilla.

oh indeed they did it in the recent updates, wonderful!
