### ISSUE TITLE
Random disconnects 

### ISSUE THREAD

**Issue by Hemp0r** [Eisbison/TheOtherRoles#313]
**Describe the bug**
After a short while the players all get disconnected from the host. Maybe its because of the new among us patch 2022.2.8s

**To Reproduce**
1. Play a round

**System (please complete the following information):**
 - OS: Windows 11
 - Among Us Version 2022.2.8s
 - TheOtherRoles Version v3.4.3
 
 Roles selected:
 - Sheriff
 - Lover
 - Lighter
 - Guesser

**Comment by Mallaris** [comment]
if the error still occurs please report on our Discord
