### ISSUE TITLE
[Bug Report] Handcuffs trigger time shield

### ISSUE THREAD

**Issue by TheKaryo** [Eisbison/TheOtherRoles#320]
**Describe the bug**
Handcuffing triggers  time shield

**To Reproduce**
1. start timeshield
2. try to handcuff as deputy
3. timeshield is triggered

**Expected behavior**
Timeshield is not triggered

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Among Us Version [e.g. v2021.11.15s]
 - TheOtherRoles Version [e.g. v3.4.3]

**Additional context**

**Comment by Mallaris** [comment]
Unfortunately we could not reproduce the problem, if you encounter it again, please contact us on our discord.
