### ISSUE TITLE
[Bug Report] deputy chance and promote

### ISSUE THREAD

**Issue by 1upCAD** [Eisbison/TheOtherRoles#329]
**Describe the bug**
- Found in the code that deputy chance depends if guesser and sheriff are in game instead of just sheriff.
- Deputy gets kill cooldown from Jackal when promoted instead of sheriff cooldown

**To Reproduce**
- Set all roles off except Sheriff and Deputy at 100%. Deputy will not be included.
- Turn on Guesser and Deputy is then added.

**Expected behavior**
Deputy should be included when everything is at 100% and when Sheriff is included and not tied to Guesser.

**Screenshots**

![image](https://user-images.githubusercontent.com/76631475/160286507-bd2f2e32-0d09-4301-8c2e-2a5acefc74f9.jpeg)

![image](https://user-images.githubusercontent.com/76631475/160286515-ed52e67f-13b1-41c6-8f15-41a80a3c9a67.jpeg)

**System (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Among Us Version [e.g. v2021.11.15s]
 - TheOtherRoles Version [e.g. v3.3.3]

**Additional context**

**Comment by 1upCAD** [comment]
Missed the "system" part.

Windows 10
Latest Among Us and Latest TOR

**Comment by Mallaris** [comment]
should already be fixed, if the problem persists please contact us on our discord. Thanks for the report
