### ISSUE TITLE
Suggested Options

### ISSUE THREAD

**Issue by MrF1uff** [Eisbison/TheOtherRoles#33]
Sheriff - Option for Sheriff and Crew Both Die when wrong

Morphling - Option to disable/enable venting

Impostors - Anonymous mode (Impostors can kill each other)

Mafia - Instead just add Janitor Option so other roles can be used

Game Options - Ability to change map and impostors in game

Players - Increase max players possibility (Crowdedmod not compatible with new version)

Balance - Option to Disable Medbay checks, Option to see vents open in Fog of War.

If I knew how to code as good as you guys I would attempt this myself. Thank you for all you do.

**Comment by Eisbison** [comment]
Please write this in the Discord feature-suggestion channel 🏁
