### ISSUE TITLE
[Bug Report] TOR mod v3.4.4 doesn't load on AU v2022.3.29s (build 1864)

### ISSUE THREAD

**Issue by homeworkprod** [Eisbison/TheOtherRoles#330]
**Describe the bug**
After the recent update of Among Us, the TOR mod no longer appears in the game's main menu after startup.

**To Reproduce**
1. Update Among Us in Steam (which currently updates it to v2022.3.29s for me).
2. Start game.
3. Verify AU version in top left.
4. Look for the usual TOR menu additions.

**Expected behavior**
TOR mod appears to be loaded.

**System (please complete the following information):**
 - OS: Debian Bullseye + updates
 - Among Us Version: v2022.3.29s
 - TheOtherRoles Version: v3.4.4

**Comment by dwd0tcom** [comment]
Fixed with #333

**Comment by homeworkprod** [comment]
Thanks a lot! I can confirm that this works.
