### ISSUE TITLE
Doesn´t get any Roles

### ISSUE THREAD

**Issue by This-Kreed** [Eisbison/TheOtherRoles#334]
I installed this mod with my friends but when we make a custom game and we made some roles on 100%  but no one gets these roles.

**Comment by dwd0tcom** [comment]
Did you turn off vanilla and turn on mod roles?

**Comment by This-Kreed** [comment]
Yes i did, i enabeld the mods( the flip was at on)

**Comment by gendelo3** [comment]
Did you set the minimum and maximum roles correctly for crewmates, neutral, impostor?

**Comment by This-Kreed** [comment]
I set minimum on 4 and max on 6 by the crewmates 1-2 neutral and Imp
