### ISSUE TITLE
[Bug Report] Buttons bug

### ISSUE THREAD

**Issue by fivefirex** [Eisbison/TheOtherRoles#335]
**Describe the bug**
I installed the latest mod with my friends. But when we’re playing, I clicked the chat button for a few time. Then I discovered that I can’t click any vote button or activity button.

**To Reproduce**
1. Click the chat button for a few time.
2. See error: you can’t click any buttons.

**Expected behavior**
I want it to be normal - all the buttons are able to click after click the chat button.

**Screenshots**
None.

**System (please complete the following information):**
 - OS: Windows 10 x64
 - Among Us Version v2022.3.29s
 - TheOtherRoles Version v3.4.5

**Additional context**
None.

**Comment by Thibault-Brocheton** [comment]
I confirme the bug
To reproduce it, spam click on the chat message button
