### ISSUE TITLE
Ingame bugs

### ISSUE THREAD

**Issue by DracoL1ch** [Eisbison/TheOtherRoles#34]
Installed the mod over default steam version
For some reason I can't benefit of Spy's ability (admin table keep showning default icons), neither can't use vents when playing as Engineer. But instead, I can see all player's nicknames all the time, properly, even when it's a Morphed or Camo'd player. Which turns those totally useless against me.
Been tested on 1.6 version, will reply if new patches fixed it.
Weird thing.

**Comment by Eisbison** [comment]
Well that's weird... test 1.8 please and keep me updated ;)

**Comment by DracoL1ch** [comment]
1.8, still the same, my game completely ignores all operations with player nicknames, be it morph or camo

**Comment by Eisbison** [comment]
ReallY weird, does the color of your name change,  if you have a special role?

**Comment by DracoL1ch** [comment]
got time master twice, had default white color and description of the role on the task bar 'crewmate'
normal red color when impostering
so I guess somehow my build is broken, but I have no idea how is it possible

**Comment by Eisbison** [comment]
Are you sure that the mod loaded prperpy?

**Comment by DracoL1ch** [comment]
I benefit of time master, camo/morph features just fine, all the issues goes down to some specific mechanics

**Comment by Eisbison** [comment]
How is your network connection?

**Comment by Eisbison** [comment]
Weird weird. Probably a small patch is coming today, where we fix a few network issues. Maybe that'll help

**Comment by Eisbison** [comment]
The hotfix coming in a few hours should fix this issue. If not please reopen it 😉
