### ISSUE TITLE
[Bug Report] Lawyer doesn't become Pursuer when target disconnects

### ISSUE THREAD

**Issue by BatmenzDW** [Eisbison/TheOtherRoles#345]
**Describe the bug**
Lawyer doesn't become pursuer when their target leaves the game

**To Reproduce**
1. Go into a meeting
2. Have lawyer's target disconnect
3. Lawyer remains as lawyer

**Expected behavior**
Lawyer becomes Pursuer

**Comment by Mallaris** [comment]
Disconects unfortunately break the mod in many places, but we try to cover as many as possible thanks for the report
