### ISSUE TITLE
Cooldowns are glitched sometimes

### ISSUE THREAD

**Issue by VonNekyia** [Eisbison/TheOtherRoles#35]
Hello,
cooldowns are sometimes at the max integer value (2147483648). 

- had this bug also in 1.7
- all roles are affected if they got an ability with a cooldown.

(had this bug with Time Master and Morphling)

**Comment by Eisbison** [comment]
How stable is your internet connection? Was it after a Shifter shofted you, or just during a normal game?

**Comment by VonNekyia** [comment]
It happend straight on, I ran from the table and time shifted after like 40 seconds of doing tasks. Then the cooldown was 2... I reported the bug because I heard serveral persons had him. We had the bug 4 times in like 10 hours of gameplay. There seems to be no obvious trigger.

**Comment by Eisbison** [comment]
It probably always happened after the first use of the button right?

**Comment by VonNekyia** [comment]
As far as I can remember before most times at first ability use

**Comment by Eisbison** [comment]
Did 1.8.2 fix it?

**Comment by Eisbison** [comment]
Closing this, since I think it has been fixed. Please reopen it if the problem still occurs
