### ISSUE TITLE
hELP mE SERVEER DONT WORK

### ISSUE THREAD

**Issue by crronen** [Eisbison/TheOtherRoles#352]
The servers for NA are literally inoperable everyone is literally frozen, I try to use a custom server putting in everything correctly and then  it also doesnt work I put my own house ip is that why? Am I supposed to use 127.0.01???? IM CONFUSED I CANT PLAY WITH MY FRIENDS!!

**Comment by Ekaeshic** [comment]
Did u use v4.1.3? if so then try downgrade to v4.1.2 as i'm currently facing the same issue in any official server region. Idk what caused the issue but I hope they fix this.

**Comment by K3ndoo** [comment]
Update Submerged. This should fix it.
