### ISSUE TITLE
[Suggestion] Butcher (impostor)

### ISSUE THREAD

**Issue by DracoL1ch** [Eisbison/TheOtherRoles#355]
Passive ability - kills up to 2 crewmates at once if they stand too close to each other. Useful against bad players who keep walking around in pairs or standing at a single point when lights out.

**Comment by Mallaris** [comment]
If you have a role suggestion feel free to submit in discord

**Comment by DracoL1ch** [comment]
> If you have a role suggestion feel free to submit in discord

Your moderator banned me there forever :)
