### ISSUE TITLE
When I put in the mod, Among Us stuck on load.

### ISSUE THREAD

**Issue by diemond16** [Eisbison/TheOtherRoles#360]
**Describe the bug**
Hello! Yesterday I updated TOR from 4.1.3 to 4.1.4, and now I'm stuck in the loading screen. I play the game from Epic Games Launcher.

**To Reproduce**
1. Install Among Us from Epic Games
2. Launch it and then close the program
3. Put in the TOR mod, doesn't matter which version
4. Start the game and you are stuck in the loading screen

**Expected behavior**
I expected the game to load in..

**Screenshots**
![image](https://user-images.githubusercontent.com/105246905/170661033-ced5cba7-a725-40c7-a0ac-975c056b5425.png)

**System:**
 - OS: Windows 10
 - Among Us Version v2022.4.19 (build num: 1886)
 - TheOtherRoles Version 4.1.4, 4.1.3, 4.1.2.....

**Additional context**
I went to sleep with Among Us running, maybe if I wait it'll load, but no. I already tried to reinstall it like 6 times, my GPU is up to date, PC restart didn't work and deleting the Innersloth folder didn't solve the issue either. For whatever reason even the versions that I could play before are not working either.

**Comment by cbru8383x** [comment]
I am having the same issue, however I am using steam. But was trying to install it to play with some friends with the same build num (1886), and couldn't get it to work. Both trying 4.1.3 and 4.1.4 and verifying file integrity and reinstalling the game.

**Comment by K3ndoo** [comment]
Don't use the updater. Reinstall the mod manually. Run Steam in the background. If this still occurs after you you reinstalled it, close the game/mod and restart it.

**Comment by Mallaris** [comment]
Reinstall the mod manually. Run Steam in the background. If this still occurs after you you reinstalled it, close the game/mod and restart it. If the problem still occurs just ask on the discord for help
