### ISSUE TITLE
add support for the latest version of among us

### ISSUE THREAD

**Issue by firefoxnightlymozzila** [Eisbison/TheOtherRoles#363]
**Is your feature request related to a problem? Please describe.**
i cannot play this mod due to the older version of among us requirement

**Describe the solution / role you'd like**
add support for the latest version

**Describe alternatives you've considered**
downgrading the game (i cannot as i use the itch.io version of the game which doesnt allow downgrading versions like steam)

**Additional context**
nope

**Comment by gendelo3** [comment]
What is the current version of among us available on itch.io (text in the upper left corner of among us)?

TheOtherRoles is compatible with the latest version of Among Us (at least on steam/epic)

**Comment by firefoxnightlymozzila** [comment]
> What is the current version of among us available on itch.io (text in the upper left corner of among us)?
> 
> TheOtherRoles is compatible with the latest version of Among Us (at least on steam/epic)

v2022.4.19i

**Comment by gendelo3** [comment]
And have you tried it and can confirm it's not working? Tor usually lists comparability to steam versions, but that doesn't mean it can't work with the small updates that are sometimes released on epic/itch apparently

**Comment by firefoxnightlymozzila** [comment]
> And have you tried it and can confirm it's not working? Tor usually lists comparability to steam versions, but that doesn't mean it can't work with the small updates that are sometimes released on epic/itch apparently

IT DOESNT FUCKING WORK I'VE TURNED OFF MY FIREWALL N SHIT IT DONT WORK
