### ISSUE TITLE
DNA sample improvement

### ISSUE THREAD

**Issue by DracoL1ch** [Eisbison/TheOtherRoles#37]
Whenever Sample is used, there must be at least 0.5s cooldown on the button for morphing.
Reason: sometimes it's not clear if Im in range with a player, and I spam the button, what causing it to morph instantly after taking DNA. It doesn't make much sense to be used this way in a normal game anyway, you won't morph while being visible by other player.

**Comment by Eisbison** [comment]
✔️

**Comment by Eisbison** [comment]
Will be introduced with todays hotfix, closing this issue ✅
