### ISSUE TITLE
Bitten by vampire while shielded

### ISSUE THREAD

**Issue by nokoji** [Eisbison/TheOtherRoles#41]
Yesterday I was bitten by a vampire while being shielded. Is this intended or a bug? I think the killer may have been laggy. Version 1.8.1

**Comment by Eisbison** [comment]
Not intended, also programmed not to happen :) Probably because of the lag... Are you using 1.8.2?

**Comment by Eisbison** [comment]
I'll close the issue for now. Please reopen it if it happens again. I checked the code and tested it, things should work 😓
