### ISSUE TITLE
Sidekick does not get Jackal

### ISSUE THREAD

**Issue by DennisI511** [Eisbison/TheOtherRoles#43]
In many games when I played Among Us  when the Jackal gets voted out the Sidekick isnt able to get the new Jackal and unable to dothe Stuff the Jackal can do. If there is any way to fix it it would be great because i think the Jackal role is one of the best addons that been created.

**Comment by Eisbison** [comment]
Working on it ✅

**Comment by Eisbison** [comment]
Fixed it in the version that will be released today/tomorrow. Closing the issue for now :)
