### ISSUE TITLE
pls update on new among us version xD

### ISSUE THREAD

**Issue by syaoranvn** [Eisbison/TheOtherRoles#46]
update pls

**Comment by manniL** [comment]
Just be patient 😋 
Some other dependencies have to be updated too, so it takes a little ;)

**Comment by FerbFloo** [comment]
Okay wow, that update is only our for a few hours, i am sure they are already working on it haha

**Comment by monodop** [comment]
Yeah, but it's nice to have an issue to track it. That way everyone knows it's not up to date yet, and that it's in progress.

**Comment by FerbFloo** [comment]
Agreed. Otherwise issues like this one will keep popping up.
