### ISSUE TITLE
I cant install the Mod

### ISSUE THREAD

**Issue by C0ldpain** [Eisbison/TheOtherRoles#50]
I have download the Zip Data and put it into a Copy of the game so i have closed the order and start the game but nothing happens i tryed it 4 times
 
Can you help me, please ?

**Comment by specalchild** [comment]
Hi there, the mod is currently out of date due to the latest update, the Developers for this modpack are waiting for an update for dependencies.
This usually takes a couple of days.

**Comment by TimmasRepo** [comment]
yeah I have the same issue

**Comment by FerbFloo** [comment]
Yeah just wait a couple of days, the old among us version should work fine tho

**Comment by Eisbison** [comment]
I'll close this for now, as already another issue exists (for the update) and this issue is related to that.
