### ISSUE TITLE
Imposters can kill as ghost

### ISSUE THREAD

**Issue by Aishir42** [Eisbison/TheOtherRoles#54]
One Imposter was dead and he still was able to kill! :D

**Comment by Eisbison** [comment]
Did everyone have tge mod installed?

**Comment by MrFawkes1337** [comment]
This is... Not one I have seen, me and some friends were playing last night. did every player have the mod, or another mod installed?

**Comment by Aishir42** [comment]
Yeah, everyone had the correct mod! They got killed by the jackal!
________________________________

**Comment by Eisbison** [comment]
Interesting... But where they ghosts on their screens or did they just remain alive?

**Comment by Aishir42** [comment]
For us she was dead, she stayed that she lived...
________________________________

**Comment by Eisbison** [comment]
We couldn't reproduce the bug, try https://github.com/Eisbison/TheOtherRoles/releases/tag/v2.1.0 and reopen the issue if it's still a thing ;)
