### ISSUE TITLE
enhancement: Custom hats

### ISSUE THREAD

**Issue by ccir2429** [Eisbison/TheOtherRoles#58]
I've seen this mod enhancement for youtubers, and wondered if you could implement it here too.
The idea is that you have a folder called `TheOtherRoles_CustomHats` or something like that, and you or the community could add hats(.png images) into the folder. 

Also custom colors, or more color variants would be nice to have too.

**Comment by Eisbison** [comment]
I really like the idea, I've also been thinking about it :) But I will have to check what it means effort wise ;)

**Comment by MrFawkes1337** [comment]
Eisbison, please take a look at my Pull request for CorsacHats [Here](https://github.com/MrFawkes1337/CorsacHats) which has support for 2021.3.31.3s. It's pretty easy Implementation :). I use a different version utilising AssetBundles for creator hats, and then a similar method as this for loading from folders for end users to add their own stuff. User added hats does seem to break compatibility, however, so might be an idea to have two separate versions for each. idk.

**Comment by ccir2429** [comment]
The only problem with CorsacHats, at least from what I know is that you can't import the hats directly from a local directory.

**Comment by MrFawkes1337** [comment]
> The only problem with CorsacHats, at least from what I know is that you can't import the hats directly from a local directory.

Actually, CorsacHats loads from the Base game directory a folder called CorsacHats, which contains *.hat.png files. So it does, actually load from a local directory. :)

**Comment by Eisbison** [comment]
Thanks for everyones input and @MrFawkes1337  thanks for the PR. I'll have a look at it tomorrow, I'm quite budy today ;)

**Comment by MrFawkes1337** [comment]
> Thanks for everyones input and @MrFawkes1337 thanks for the PR. I'll have a look at it tomorrow, I'm quite budy today ;)

Anytime man :). It can probably be cleaned up, but it does work for testing purposes haha.

**Comment by volt26** [comment]
I would love to see this added in The Other Roles. Meanwhile MrFawkes1337, do you have a compiled dll that works with the 2021.4.12? (or newer version). I would gladly stich with 2021.3.31 but I can't play ToR + crowded with this version. But ToR has crowded working with 2021.4.12 which means it would be a huge improvement if the standalone CorsacHats had a working version with 2021.4.12 :)

**Comment by MrFawkes1337** [comment]
> I would love to see this added in The Other Roles. Meanwhile MrFawkes1337, do you have a compiled dll that works with the 2021.4.12? (or newer version). I would gladly stich with 2021.3.31 but I can't play ToR + crowded with this version. But ToR has crowded working with 2021.4.12 which means it would be a huge improvement if the standalone CorsacHats had a working version with 2021.4.12 :)

Check the Link above, I just uploaded the CorsacHats update

**Comment by volt26** [comment]
> Check the Link above, I just uploaded the CorsacHats update

Thank you very much! You are my hero!

**Comment by Eisbison** [comment]
I'll close this as it's already paritally in the mod and because it will be available for everyone tomorrow.
