### ISSUE TITLE
Shifter swapping with engineer while engineer is hopping into the vent results in now shifter not being able to exit the vent.

### ISSUE THREAD

**Issue by ThaSiouL** [Eisbison/TheOtherRoles#6]
We just had this in a game on the 1.3 version. the now shifter could vent around but not exit the vents until a round was called.
A possible solution would be to make everyone have the vent ability while inside vents? and just take it away after they use it to get out?

**Comment by Eisbison** [comment]
Good catch. I just fixed it, was a one liner. Also reminded me of something I forgot: All roles with an effect on players should not be able to target people in vents (i.e. Seer, Sheriff, ...). They only player that is able to do that should be the impostor, which can kill the Engineer if he the imposter stands beside the vent that the Engineer sits in.

Bugfix will be included in the update I release in a few hours ✅
