### ISSUE TITLE
Time Master shield

### ISSUE THREAD

**Issue by DracoL1ch** [Eisbison/TheOtherRoles#61]
For some reason it says cooldowns arent affected, but in my games imps keep killing the time master after the rewind being triggered by the same impostor. Either description is incorrect, either the behaviour.

**Comment by Eisbison** [comment]
Well it's the same as for the Medic shield, the cd of the imp will not be triggered :D Other cooldowns don't turn back. You basically have to avoid that the same situation happens after rewinding.

**Comment by Eisbison** [comment]
But I will update the description

**Comment by Eisbison** [comment]
But I will update the description

**Comment by DracoL1ch** [comment]
yeah, exactly, I've read the description and it was confusing as hell for me
