### ISSUE TITLE
Antivirus detection

### ISSUE THREAD

**Issue by msentuerk** [Eisbison/TheOtherRoles#63]
Hello,
my antivirus software is detecting a virus with the current release.

**\Among Us\BepInEx\unhollowed\UnityEngine.ClusterInputModule.dll** infected with **Gen:Variant.Bulz.424443** when starting Among Us.

I hope this can be fixed in the future releases.

Kind Regard,
Mehmet

**Comment by MrFawkes1337** [comment]
Just FYI, this file is generated from your game files, not the mod. When you first run BepInEx, it makes a decompiled / Slightly deobfuscated dump of the game (This is the Unhollowed Folder), which is why it takes longer to start on the first run. This isn't something Eisbison can fix, as it's your Antivirus picking up a false positive. Just add an exception for the Among us folder, and you'll be fine.

**Comment by msentuerk** [comment]
I've allready tryed it vanilla.  I dont get the same notification!

**Comment by MrFawkes1337** [comment]
> I've allready tryed it vanilla. I dont get the same notification!

Read my comment again. This file is generated when BepInEx makes a semi decompiled dump of your game. YOUR ANTIVIRUS is detecting it as a FALSE POSITIVE. This is NOT something the MOD DEVELOPER can fix, this is UP TO YOU to follow advice on how to fix. You can close the issue now, and follow instructions in my previous comment on what you need to do. No point spamming the issues section when its your PC that has the crappy antivirus.

**Comment by msentuerk** [comment]
I can understand your opinion to that, but why the detection is not happening in a vanilla based Among Us installation?

**Comment by MrFawkes1337** [comment]
> I can understand your opinion to that, but why the detection is not happening in a vanilla based Among Us installation?

Because Vanilla based Among Us doesn't ship with BepInEx, which is what actually creates the Unhollowed folder. As I said, make an exception for the game folder, or change antivirus. The mod is safe, but you will have the issue regardless of mod because they all use BepInEx.

**Comment by msentuerk** [comment]
Thanks for the reply again. I tryed the same with another mod -> slushiegoose/Town-Of-Us, no notification/detection.

**Comment by MrFawkes1337** [comment]
> Thanks for the reply again. I tryed the same with another mod -> slushiegoose/Town-Of-Us, no notification/detection.

Well, considering how many people use / have used the mod and have no issues, im still inclined to say its a you issue, not the mod. My experience is fine. maybe try moving TheOtherRoles.dll from the BepInEx/Plugins folder in the .zip file to the Town of Us install, and deleting Town of Us.
