### ISSUE TITLE
Some Bugs Found

### ISSUE THREAD

**Issue by jocker1289** [Eisbison/TheOtherRoles#64]
Good evening everyone,

we found some bugs in the game.

The first thing that is really annoying when the round starts that people cannot move or after a meeting that people can no longer move, only after you have clicked on the gear (options) then it starts.

The second bug we found is that the medic simply randomly shields someone at the beginning and you no longer have a choice of who you want to shield or not.

Third, the detective sees footprints that he should never see. E.g. of dead players

The time master would have to be set back, not that he has his time sign but that he can simply turn back the time as normal.

**Comment by AchimGrube** [comment]
Can confirm the detective bug. Impostor footprints can be seen where the kill happened after meeting.

**Comment by Hexolei04** [comment]
Hey ich wollte sagen das die Fähigkeit von dem Timemaster ist das er einen timeshild hat also wenn er gekilled wird wo er die Fähigkeit eingesetzt hat das dan die zeit zurückgesetzt wird das er sagen könnte wer der Imposter ist

**Comment by PureStream** [comment]
The footprints seen by the detective also last unexpectedly long than in the setting.
When the setting allows the imposter to kill the imposter when there is the spy, the vampire seems to be able to bite and kill the spy while the bite will not kill the vampire's imposter friend.

**Comment by Eisbison** [comment]
> Hey ich wollte sagen das die Fähigkeit von dem Timemaster ist das er einen timeshild hat also wenn er gekilled wird wo er die Fähigkeit eingesetzt hat das dan die zeit zurückgesetzt wird das er sagen könnte wer der Imposter ist

For that reason the kill cooldown does not reset and the TimeMaster has to run very fast such that the impostor doesn't catch him again

**Comment by Eisbison** [comment]
> Good evening everyone,
> 
> we found some bugs in the game.
> 
> The first thing that is really annoying when the round starts that people cannot move or after a meeting that people can no longer move, only after you have clicked on the gear (options) then it starts.
> 
> The second bug we found is that the medic simply randomly shields someone at the beginning and you no longer have a choice of who you want to shield or not.
> 
> Third, the detective sees footprints that he should never see. E.g. of dead players
> 
> The time master would have to be set back, not that he has his time sign but that he can simply turn back the time as normal.

1) It's a bug that Among Us introduced, not us. But we'll fix it in our next version until they fix it.

2) Could not reproduce this, please ping me if it happens again

3) We're aware of that bug and working on it. Seems to be something with the Airship, we're not quite sure yet.

4) No, we won't reset the TimeMaster. The role didn't work in many different ways... You could not use the revive option, as revives just don't work in this game. If you let the TimeMaster rewind together with all the other players, then the ability was just useless, as it wouldn't change anything. If you let everyone except for the Timemaster rewind, then he could just use rewind in the beginning and everyone would know that he is a Crewmate  as he's the only one that doesn't rewind... and hardproofs are also bad. We discussed this and all agreed on the new Time Master to add much more to the game as the old one. He shields himself, rewinds and then runs for his life to prevent the same thing from happening again.

**Comment by Eisbison** [comment]
> The footprints seen by the detective also last unexpectedly long than in the setting.
> When the setting allows the imposter to kill the imposter when there is the spy, the vampire seems to be able to bite and kill the spy while the bite will not kill the vampire's imposter friend.

We're aware of that and working on it, thanks for your report ;)
