### ISSUE TITLE
[BUG] Eraser can remove role but kill button from Vampire is removed

### ISSUE THREAD

**Issue by Matze500** [Eisbison/TheOtherRoles#65]
If the Eraser removes the role from the vampire. The vampire role is removed but he can not kill anyone anymore.
The countdown starts but there is no kill button.

![8beff38d-5dad-44aa-964b-d458c5be16a4](https://user-images.githubusercontent.com/1665678/114287372-8eea6600-9a66-11eb-9b75-9e3261aa2efe.jpg)

**Comment by Eisbison** [comment]
Thank you for your report, we'll fix it with the next update.
