### ISSUE TITLE
2.1.0 theOtheRoles Bug

### ISSUE THREAD

**Issue by VikingCR** [Eisbison/TheOtherRoles#66]
Hey,
I just downloaded your .zip folder and copy paste the Content in the Among Us Folder. Afterthat I started the AmongUs Game and it was still the same as the normal game without the Roles. 

Here are 2 screenshots of my folder and my game.
Folder: https://drive.google.com/file/d/1JfiJB0VL3b06eDvSgqOAH0CHrZej2yHe/view?usp=sharing 
Game: https://drive.google.com/file/d/1D5ba6x8-l0tqf8ovTxSDNtyxVdFfVJDL/view?usp=sharing

I would really appreciate it if you can help me to solve my problem or explain what I did wrong. 
Greetings,
Viking | Liam

**Comment by Eisbison** [comment]
Well what does it say for the required Among us version... **2021.3.31.3s** 👍  What do you have? :D Opt out the public beta in steam and reinstall among us
