### ISSUE TITLE
TheOtherRolesBug 

### ISSUE THREAD

**Issue by VikingCR** [Eisbison/TheOtherRoles#67]
Hey Eisbison,

I reinstalled Among Us without the public beta and now I have the correct version of Among Us but it still doesn't work. I don't know what is wrong now :/ 

Folder: https://drive.google.com/file/d/1EKXTMOJXZZ5TFkaBin_iFiqUx7CeuT5z/view?usp=sharing 
Game: https://drive.google.com/file/d/1GXElWzEnoFXz_GChMktAgoXT7kMNaHPT/view?usp=sharing

I very appreciate your support and help,
Greetings,
Viking | Liam

**Comment by Eisbison** [comment]
You are not supposed to download the source code, but the latest release... . You are using the wrong folder here. Use that one https://github.com/Eisbison/TheOtherRoles/releases/download/v2.1.0/TheOtherRoles.zip
