### ISSUE TITLE
> 10 players only works when CustomServer is an IP address

### ISSUE THREAD

**Issue by neomis** [Eisbison/TheOtherRoles#71]
If you put a domain name in the Custom Server section this code fails:
`public static bool isCustomServer() {
            return DestroyableSingleton<ServerManager>.CHNDKKBEIDG?.KEABFOHAECE == TheOtherRolesPlugin.Ip.Value;
        }
`

**Comment by InLoveWithLua** [comment]
Domain is working fine for me

**Comment by Eisbison** [comment]
Should be working with v2.2.1 and the v2.2.2 we're releasing today. I'll close the issue for now 👍
