### ISSUE TITLE
Error message when host leaves the game

### ISSUE THREAD

**Issue by neomis** [Eisbison/TheOtherRoles#72]
Player 1 creates a game on a custom server.  Player 2 joins.  Player 1 leaves the game and player 2 gets this message (intermittently).

<Player> has an outdated or no version of The Other Roles

Both players have the exact same mods installed.
![0](https://user-images.githubusercontent.com/15381645/114616987-c7579300-9c64-11eb-8981-4b5c54739395.png)

**Comment by Eisbison** [comment]
It's because only the server host keeps the info about the version handshake :) Hence if the host leaves, the new host doesn't have the handshake info. You should not worry about this, we'll improve the handshake with the next update :)
