### ISSUE TITLE
NullPointerException somewhere

### ISSUE THREAD

**Issue by TheKaryo** [Eisbison/TheOtherRoles#73]
[preloader_20210414_065341_362.log](https://github.com/Eisbison/TheOtherRoles/files/6308514/preloader_20210414_065341_362.log)
friend of mine keeps getting that error message when booting

**Comment by Eisbison** [comment]
Seems BepInEx related to me. But tbh I don't know what do to there :D vsredist installed?

**Comment by MrFawkes1337** [comment]
Thats 100% related to BepInEx. Try a clean install of Among Us, then Install BepInEx ONLY, and see what happens. if it all loads, start installing mods

**Comment by Eisbison** [comment]
Can we close this? @TheKaryo

**Comment by TheKaryo** [comment]
Yes reinstalling BepInEx worked
