### ISSUE TITLE
FPS Spikes all few seconds

### ISSUE THREAD

**Issue by HutMitMann** [Eisbison/TheOtherRoles#75]
Hey, since 1.8 I have only with OtherRoles some FPS Spikes. Normal Among Us works fine with 60FPS and no spikes.

Is this a common problem? Oh and Yes, my PC is good enough ;) 

Thanks for your Work! Love this Game :D

**Comment by Eisbison** [comment]
Anyone else having this problem? What OS are you playing on?

**Comment by HutMitMann** [comment]
Windows10

**Comment by SinJin59** [comment]
Hi. I´ve got 2 people also with lags. I asked them about their Setup. Hope it helps finding the problem.
1. Laptop:
System: Windows 10 Home / 64Bit
Graphic Card: Intel(R) HD Graphics
Processor: Intel(R) Celeron(R) CPU N2940 @ 1.83 GHz
Network Adapter WLAN: Realtek RTL8723BE Wireless LAN 802.11n PCI-E NIC#2
RAM: 4GB

2. Tower Setup:
System: Windows 10 Home / 64Bit
Graphic Card: Nvidia GeForce GTX 1060 6GB
Processor: Intel Core i5-8600k 3.60GHz
Network Adapter LAN: Realtek PCIe GbE Family Controller
RAM: 32GB DDR4 (2x8 and 1x16)

**Comment by HutMitMann** [comment]
My System is completely different then yours, so i dont think it depends on the PC specs.

I have 
- Windows 10 Pro
- AMD FX(tm)-8120 Eight-Core Processor 3.10 GHz
- 16GB DDR3 Ram
- AMD Radeon HD 7800 Series

Ich weiß doch auch nicht weiter :D

**Comment by Eisbison** [comment]
Unfortunately I don't really know how to resolve this issue :/

**Comment by SinJin59** [comment]
@Eisbison Could it be something with unity? Maybe some garbage collection that is not working probably, when starting the game? People not only got in game problems. The problems seems to start by, joining the lobby or starting the mod.

**Comment by Eisbison** [comment]
Idk, I'd have to test with someone and remove code step by step to find the source of the problem... I'll close this issue becaise now there are two identical ones (#107 )
