### ISSUE TITLE
Freeplay does not work

### ISSUE THREAD

**Issue by Bhenry4** [Eisbison/TheOtherRoles#76]
When you start freeplay it says "Normally The Crew would have just won because The Imposter is dead. For freeplay, we revive everybody instead."
![freeplay](https://user-images.githubusercontent.com/82593996/114880444-1241e980-9dd0-11eb-8805-dc4523da6d92.png)

**Comment by Eisbison** [comment]
We're aware of this issue, but it's not high up on the priority list right now, as it's not really important :D

**Comment by Eisbison** [comment]
@Bhenry4 The fix comes with the next update ;)

**Comment by Eisbison** [comment]
Done :)
