### ISSUE TITLE
option to disable other regions

### ISSUE THREAD

**Issue by neomis** [Eisbison/TheOtherRoles#81]
With the > 10 player mod requiring custom Impostor Servers to work.  Can there be a true false flag in the config file that removes NA, EU, and Asia?  Basically, only show the Custom Server option?

**Comment by smarschollek** [comment]
I have created a fix for that because i needed the same feature i could create a PR

**Comment by neomis** [comment]
Since you already added the pull request.  Can you throw in the variable Name "Custom Server Name" so we can name the "region"
`public static ConfigEntry<string> Name {get; set;}`
`Name = Config.Bind("Custom", "Custom Server Name", "Custom");`
`IRegionInfo customRegion = new DnsRegionInfo(Ip.Value, Name.Value, StringNames.NoTranslation, Ip.Value, Port.Value).Cast<IRegionInfo>();
            `
I guess I need to figure out how to use Github so I can create pull requests (I only use GitLab at work).

**Comment by EoF-1141** [comment]
Both of these things are in my pre-release version.

Code also needs some review, as the way it's implemented kinda obsolotes the "regions" variable entirely.
Also bad use of ternary there.

**Comment by smarschollek** [comment]
@EoF-1141 you are right the code was not very readable. With the name config change i also changed that part.

**Comment by Eisbison** [comment]
Do we still need this or do you think things are okay as they are right now?

**Comment by Eisbison** [comment]
I guess so, otherwise please reopen the issue
