### ISSUE TITLE
[suggestion] Marker "quests done X%"

### ISSUE THREAD

**Issue by DracoL1ch** [Eisbison/TheOtherRoles#86]
A marker next to player's nickname, which is only visible to ghosts.
It applies to ghosts only - only ghosts are able to see those, and numbers only displayed over dead bodies.
Reason - another quality of life change to detect slackers and  remove them from games
Impostors/questless roles always have 100% done visible
This number ONLY affects ghosts therefore it cannot affect gameplay anyhow
What do you think?

**Comment by FUKU-00** [comment]
Agree! That would be nice!

**Comment by Eisbison** [comment]
Included in v2.4.0
