### ISSUE TITLE
Something went wrong with signing into your account

### ISSUE THREAD

**Issue by sabygrande** [Eisbison/TheOtherRoles#92]
Hi, i can't play the other Roles mod with my own account or username because theres always an error popping up, which makes it basically impossible to use your own name in game
<img width="704" alt="error" src="https://user-images.githubusercontent.com/83013107/115709271-52294380-a371-11eb-830d-89aa50140ce3.PNG">

**Comment by FerbFloo** [comment]
You can change your name manually, by going to the Among Us directory found in AppData and adjusting the PlayerPrefs-File using a text editor. It stores your username, current hat/skin/color combination and whether or not you are able to use the free chat. This is, of course, just a temporary solution.

**Comment by mrlary** [comment]
Ich habe das gleiche Problem, verstehe den Lösungspfad nicht. Bitte einmal genau detailliert aufführen was gemacht werden soll. Finde die Datei AppData nicht und PlayerPrefs-Datei auch nicht.

**Comment by Eisbison** [comment]
You should be able to sign in if you keep Steam open in the background

**Comment by mrlary** [comment]
leider nein

**Comment by MrFawkes1337** [comment]
this is due to Steam being closed. Just Open steam and will work fine.

**Comment by Eisbison** [comment]
Did you figure it out @mrlary  @sabygrande ?

**Comment by mrlary** [comment]
ne leider nein

**Comment by mrlary** [comment]
okay, funktioniert. Starte die .exe als Admin.

**Comment by ccir2429** [comment]
one other  solution is to start normal among us, log in(only first time), after that start modded among us.
