### ISSUE TITLE
No way to test the roles

### ISSUE THREAD

**Issue by AlmightyAnubis** [Eisbison/TheOtherRoles#94]
Especially for new players to the mod, there are many new roles and testing them out would be quite usefull for them. I don't know if it is possible, but I think it would be a nice idea, that you can test the roles in the freeplay mode. Maybe not every role is usefull the (for example the Time master) but some roles can be testet, which would help some beginners.

**Comment by Eisbison** [comment]
You can just open mutliple game instances and start a local game. That's perfect for testing.
