### ISSUE TITLE
Wrong message with incompatible version

### ISSUE THREAD

**Issue by viseradius** [Eisbison/TheOtherRoles#95]
The host receives the message that a player has an outdated version, while the player has a newer version.

I encountered it with a player using 2.4 and the host used 2.3

**Comment by EoF-1141** [comment]
So it is the wrong version.
If someone uses 2.4, while the host has 2.3, then the non host has the wrong version.
Then he should either grab the version, the host is playing, or tell the host to update.

**Comment by viseradius** [comment]
But it was quiet confusing that the host received that message. We told that player to update until we realised that there was an update. 

You’re right. It’s the wrong version but the message could be more specific. 

Player version > mod version => message „player has a newer version“

it should be an easy change.

**Comment by Eisbison** [comment]
We'll address this with tomorrows update. I'll close the issue after that.
