### ISSUE TITLE
Game Displaying the wrong Mod Settings

### ISSUE THREAD

**Issue by KindofkidGitHub** [Eisbison/TheOtherRoles#96]
I was playing Among Us normally with mods until i noticed that every single lobby had the same mod settings so i though hmmm there must be something off. so i went and create a game changed something with the mod settings and it showed the same thing on other lobbys. and its defenitly not people getting searched with the same mod settings something was off some had them still all off. please i need a fix for this bug.

**Comment by Eisbison** [comment]
Did everyone have the same mod version?  Can't reproduce this, it seems like an installation/version issue on your side.

**Comment by Eisbison** [comment]
Resolved :)
