### ISSUE TITLE
Player gets out of bounds as child when trying to use ladder on Airship

### ISSUE THREAD

**Issue by Neolyum** [Eisbison/TheOtherRoles#98]
When trying to use the small ladder below the platform as child, the player doesn't get to the ground and begins to move outside the ship. The ladder is reusable, so the player is not stuck, but without the ladder the player cannot get back to the ship.

I can paste a clip showing the bug, if requested! :)

**Comment by Eisbison** [comment]
Are you sure that you're on the newest version of the mod? I can't reproduce the bug. We had that bug in earlier versions of the mod but it should be fixed.

**Comment by Neolyum** [comment]
oh than please nevermind, I had this bug last week and I am not entirely sure, if we were on the last version, so propably we weren't xD If I experience it again, I will write again :)
